import { writeFileSync } from "fs"
import { join } from "path"

function esc(s) {
  return s.replace(/"/g, '\\"')
}

function makeWordFile(lang, prefix, wordData, sentenceData) {
  let code = `import type { Word, Sentence } from "@/lib/types"\n\n`
  code += `export const ${lang}Words: Word[] = [\n`
  for (const w of wordData) {
    code += `  { id: "${prefix}-${w.id}", source: "${esc(w.s)}", target: "${esc(w.t)}"${w.r ? `, transliteration: "${esc(w.r)}"` : ""}, category: "${esc(w.c)}" },\n`
  }
  code += `]\n\n`
  code += `export const ${lang}Sentences: Sentence[] = [\n`
  for (const s of sentenceData) {
    code += `  { id: "${prefix}-s-${s.id}", source: "${esc(s.s)}", target: "${esc(s.t)}"${s.r ? `, transliteration: "${esc(s.r)}"` : ""} },\n`
  }
  code += `]\n`
  const dir = join(process.cwd(), "src", "data")
  writeFileSync(join(dir, `${lang}.ts`), code, "utf8")
  console.log(`Wrote ${lang}.ts: ${wordData.length} words, ${sentenceData.length} sentences`)
}

// ─── Chinese ──────────────────────────────────────────────────────────
// Word format: { s: source, t: target, r: pinyin, c: category }
const zhWords = [
  {s:"Hello", t:"你好", r:"nǐ hǎo", c:"Greetings"},
  {s:"Good morning", t:"早上好", r:"zǎo shang hǎo", c:"Greetings"},
  {s:"Good afternoon", t:"下午好", r:"xià wǔ hǎo", c:"Greetings"},
  {s:"Good evening", t:"晚上好", r:"wǎn shang hǎo", c:"Greetings"},
  {s:"Goodbye", t:"再见", r:"zài jiàn", c:"Greetings"},
  {s:"See you later", t:"回头见", r:"huí tóu jiàn", c:"Greetings"},
  {s:"See you tomorrow", t:"明天见", r:"míng tiān jiàn", c:"Greetings"},
  {s:"Thank you", t:"谢谢", r:"xiè xiè", c:"Greetings"},
  {s:"Thanks a lot", t:"非常感谢", r:"fēi cháng gǎn xiè", c:"Greetings"},
  {s:"You're welcome", t:"不客气", r:"bú kè qì", c:"Greetings"},
  {s:"Please", t:"请", r:"qǐng", c:"Greetings"},
  {s:"Excuse me", t:"打扰一下", r:"dǎ rǎo yī xià", c:"Greetings"},
  {s:"Sorry", t:"对不起", r:"duì bu qǐ", c:"Greetings"},
  {s:"How are you?", t:"你好吗", r:"nǐ hǎo ma", c:"Greetings"},
  {s:"I'm fine", t:"我很好", r:"wǒ hěn hǎo", c:"Greetings"},
  {s:"Nice to meet you", t:"很高兴认识你", r:"hěn gāo xìng rèn shí nǐ", c:"Greetings"},
  {s:"Welcome", t:"欢迎", r:"huān yíng", c:"Greetings"},
  {s:"Cheers", t:"干杯", r:"gān bēi", c:"Greetings"},
  {s:"Good luck", t:"祝你好运", r:"zhù nǐ hǎo yùn", c:"Greetings"},
  {s:"Take care", t:"保重", r:"bǎo zhòng", c:"Greetings"},
  {s:"Long time no see", t:"好久不见", r:"hǎo jiǔ bú jiàn", c:"Greetings"},
  {s:"What's up?", t:"怎么了", r:"zěn me le", c:"Greetings"},
  {s:"Likewise", t:"彼此彼此", r:"bǐ cǐ bǐ cǐ", c:"Greetings"},
  {s:"How are things?", t:"最近怎么样", r:"zuì jìn zěn me yàng", c:"Greetings"},
  {s:"Bless you", t:"保佑你", r:"bǎo yòu nǐ", c:"Greetings"},
  // Numbers
  {s:"Zero", t:"零", r:"líng", c:"Numbers"},
  {s:"One", t:"一", r:"yī", c:"Numbers"},
  {s:"Two", t:"二", r:"èr", c:"Numbers"},
  {s:"Three", t:"三", r:"sān", c:"Numbers"},
  {s:"Four", t:"四", r:"sì", c:"Numbers"},
  {s:"Five", t:"五", r:"wǔ", c:"Numbers"},
  {s:"Six", t:"六", r:"liù", c:"Numbers"},
  {s:"Seven", t:"七", r:"qī", c:"Numbers"},
  {s:"Eight", t:"八", r:"bā", c:"Numbers"},
  {s:"Nine", t:"九", r:"jiǔ", c:"Numbers"},
  {s:"Ten", t:"十", r:"shí", c:"Numbers"},
  {s:"Eleven", t:"十一", r:"shí yī", c:"Numbers"},
  {s:"Twelve", t:"十二", r:"shí èr", c:"Numbers"},
  {s:"Thirteen", t:"十三", r:"shí sān", c:"Numbers"},
  {s:"Fourteen", t:"十四", r:"shí sì", c:"Numbers"},
  {s:"Fifteen", t:"十五", r:"shí wǔ", c:"Numbers"},
  {s:"Sixteen", t:"十六", r:"shí liù", c:"Numbers"},
  {s:"Seventeen", t:"十七", r:"shí qī", c:"Numbers"},
  {s:"Eighteen", t:"十八", r:"shí bā", c:"Numbers"},
  {s:"Nineteen", t:"十九", r:"shí jiǔ", c:"Numbers"},
  {s:"Twenty", t:"二十", r:"èr shí", c:"Numbers"},
  {s:"Thirty", t:"三十", r:"sān shí", c:"Numbers"},
  {s:"Forty", t:"四十", r:"sì shí", c:"Numbers"},
  {s:"Fifty", t:"五十", r:"wǔ shí", c:"Numbers"},
  {s:"Sixty", t:"六十", r:"liù shí", c:"Numbers"},
  {s:"Seventy", t:"七十", r:"qī shí", c:"Numbers"},
  {s:"Eighty", t:"八十", r:"bā shí", c:"Numbers"},
  {s:"Ninety", t:"九十", r:"jiǔ shí", c:"Numbers"},
  {s:"One hundred", t:"一百", r:"yī bǎi", c:"Numbers"},
  {s:"One thousand", t:"一千", r:"yī qiān", c:"Numbers"},
  {s:"Ten thousand", t:"一万", r:"yī wàn", c:"Numbers"},
  // Colors
  {s:"Red", t:"红色", r:"hóng sè", c:"Colors"},
  {s:"Blue", t:"蓝色", r:"lán sè", c:"Colors"},
  {s:"Green", t:"绿色", r:"lǜ sè", c:"Colors"},
  {s:"Yellow", t:"黄色", r:"huáng sè", c:"Colors"},
  {s:"Black", t:"黑色", r:"hēi sè", c:"Colors"},
  {s:"White", t:"白色", r:"bái sè", c:"Colors"},
  {s:"Gray", t:"灰色", r:"huī sè", c:"Colors"},
  {s:"Brown", t:"棕色", r:"zōng sè", c:"Colors"},
  {s:"Orange", t:"橙色", r:"chéng sè", c:"Colors"},
  {s:"Pink", t:"粉色", r:"fěn sè", c:"Colors"},
  {s:"Purple", t:"紫色", r:"zǐ sè", c:"Colors"},
  {s:"Gold", t:"金色", r:"jīn sè", c:"Colors"},
  {s:"Silver", t:"银色", r:"yín sè", c:"Colors"},
  {s:"Light", t:"浅色", r:"qiǎn sè", c:"Colors"},
  {s:"Dark", t:"深色", r:"shēn sè", c:"Colors"},
  {s:"Bright", t:"明亮", r:"míng liàng", c:"Colors"},
  {s:"Colorful", t:"多彩", r:"duō cǎi", c:"Colors"},
  {s:"Transparent", t:"透明", r:"tòu míng", c:"Colors"},
  {s:"Rainbow", t:"彩虹", r:"cǎi hóng", c:"Colors"},
  {s:"Beige", t:"米色", r:"mǐ sè", c:"Colors"},
  // Food (reduced set)
  {s:"Water", t:"水", r:"shuǐ", c:"Food & Drink"},
  {s:"Coffee", t:"咖啡", r:"kā fēi", c:"Food & Drink"},
  {s:"Tea", t:"茶", r:"chá", c:"Food & Drink"},
  {s:"Milk", t:"牛奶", r:"niú nǎi", c:"Food & Drink"},
  {s:"Juice", t:"果汁", r:"guǒ zhī", c:"Food & Drink"},
  {s:"Beer", t:"啤酒", r:"pí jiǔ", c:"Food & Drink"},
  {s:"Wine", t:"红酒", r:"hóng jiǔ", c:"Food & Drink"},
  {s:"Rice", t:"米饭", r:"mǐ fàn", c:"Food & Drink"},
  {s:"Bread", t:"面包", r:"miàn bāo", c:"Food & Drink"},
  {s:"Chicken", t:"鸡肉", r:"jī ròu", c:"Food & Drink"},
  {s:"Meat", t:"肉", r:"ròu", c:"Food & Drink"},
  {s:"Fish", t:"鱼", r:"yú", c:"Food & Drink"},
  {s:"Egg", t:"鸡蛋", r:"jī dàn", c:"Food & Drink"},
  {s:"Cheese", t:"奶酪", r:"nǎi lào", c:"Food & Drink"},
  {s:"Soup", t:"汤", r:"tāng", c:"Food & Drink"},
  {s:"Salad", t:"沙拉", r:"shā lā", c:"Food & Drink"},
  {s:"Fruit", t:"水果", r:"shuǐ guǒ", c:"Food & Drink"},
  {s:"Vegetable", t:"蔬菜", r:"shū cài", c:"Food & Drink"},
  {s:"Apple", t:"苹果", r:"píng guǒ", c:"Food & Drink"},
  {s:"Banana", t:"香蕉", r:"xiāng jiāo", c:"Food & Drink"},
  {s:"Orange", t:"橙子", r:"chéng zi", c:"Food & Drink"},
  {s:"Strawberry", t:"草莓", r:"cǎo méi", c:"Food & Drink"},
  {s:"Watermelon", t:"西瓜", r:"xī guā", c:"Food & Drink"},
  {s:"Grape", t:"葡萄", r:"pú táo", c:"Food & Drink"},
  {s:"Tomato", t:"番茄", r:"fān qié", c:"Food & Drink"},
  {s:"Potato", t:"土豆", r:"tǔ dòu", c:"Food & Drink"},
  {s:"Onion", t:"洋葱", r:"yáng cōng", c:"Food & Drink"},
  {s:"Carrot", t:"胡萝卜", r:"hú luó bo", c:"Food & Drink"},
  {s:"Garlic", t:"大蒜", r:"dà suàn", c:"Food & Drink"},
  {s:"Corn", t:"玉米", r:"yù mǐ", c:"Food & Drink"},
  {s:"Salt", t:"盐", r:"yán", c:"Food & Drink"},
  {s:"Sugar", t:"糖", r:"táng", c:"Food & Drink"},
  {s:"Honey", t:"蜂蜜", r:"fēng mì", c:"Food & Drink"},
  {s:"Chocolate", t:"巧克力", r:"qiǎo kè lì", c:"Food & Drink"},
  {s:"Cake", t:"蛋糕", r:"dàn gāo", c:"Food & Drink"},
  {s:"Ice cream", t:"冰淇淋", r:"bīng qí lín", c:"Food & Drink"},
  {s:"Breakfast", t:"早餐", r:"zǎo cān", c:"Food & Drink"},
  {s:"Lunch", t:"午餐", r:"wǔ cān", c:"Food & Drink"},
  {s:"Dinner", t:"晚餐", r:"wǎn cān", c:"Food & Drink"},
  {s:"Restaurant", t:"餐厅", r:"cān tīng", c:"Food & Drink"},
  {s:"Hungry", t:"饿", r:"è", c:"Food & Drink"},
  {s:"Thirsty", t:"渴", r:"kě", c:"Food & Drink"},
  {s:"Delicious", t:"好吃", r:"hǎo chī", c:"Food & Drink"},
  {s:"Spicy", t:"辣", r:"là", c:"Food & Drink"},
  {s:"Sweet", t:"甜", r:"tián", c:"Food & Drink"},
  {s:"Sour", t:"酸", r:"suān", c:"Food & Drink"},
  {s:"Bitter", t:"苦", r:"kǔ", c:"Food & Drink"},
  {s:"To eat", t:"吃", r:"chī", c:"Food & Drink"},
  {s:"To drink", t:"喝", r:"hē", c:"Food & Drink"},
  {s:"To cook", t:"做饭", r:"zuò fàn", c:"Food & Drink"},
  {s:"To cut", t:"切", r:"qiē", c:"Food & Drink"},
  {s:"To order", t:"点菜", r:"diǎn cài", c:"Food & Drink"},
  // Animals
  {s:"Dog", t:"狗", r:"gǒu", c:"Animals"},
  {s:"Cat", t:"猫", r:"māo", c:"Animals"},
  {s:"Bird", t:"鸟", r:"niǎo", c:"Animals"},
  {s:"Horse", t:"马", r:"mǎ", c:"Animals"},
  {s:"Cow", t:"牛", r:"niú", c:"Animals"},
  {s:"Pig", t:"猪", r:"zhū", c:"Animals"},
  {s:"Sheep", t:"羊", r:"yáng", c:"Animals"},
  {s:"Rabbit", t:"兔子", r:"tù zi", c:"Animals"},
  {s:"Elephant", t:"大象", r:"dà xiàng", c:"Animals"},
  {s:"Lion", t:"狮子", r:"shī zi", c:"Animals"},
  {s:"Tiger", t:"老虎", r:"lǎo hǔ", c:"Animals"},
  {s:"Bear", t:"熊", r:"xióng", c:"Animals"},
  {s:"Monkey", t:"猴子", r:"hóu zi", c:"Animals"},
  {s:"Snake", t:"蛇", r:"shé", c:"Animals"},
  {s:"Turtle", t:"乌龟", r:"wū guī", c:"Animals"},
  {s:"Frog", t:"青蛙", r:"qīng wā", c:"Animals"},
  {s:"Eagle", t:"鹰", r:"yīng", c:"Animals"},
  {s:"Butterfly", t:"蝴蝶", r:"hú dié", c:"Animals"},
  {s:"Bee", t:"蜜蜂", r:"mì fēng", c:"Animals"},
  {s:"Whale", t:"鲸鱼", r:"jīng yú", c:"Animals"},
  {s:"Dolphin", t:"海豚", r:"hǎi tún", c:"Animals"},
  {s:"Shark", t:"鲨鱼", r:"shā yú", c:"Animals"},
  {s:"Penguin", t:"企鹅", r:"qǐ é", c:"Animals"},
  {s:"Duck", t:"鸭", r:"yā", c:"Animals"},
  // Body
  {s:"Head", t:"头", r:"tóu", c:"Body"},
  {s:"Hair", t:"头发", r:"tóu fa", c:"Body"},
  {s:"Face", t:"脸", r:"liǎn", c:"Body"},
  {s:"Eye", t:"眼睛", r:"yǎn jīng", c:"Body"},
  {s:"Ear", t:"耳朵", r:"ěr duo", c:"Body"},
  {s:"Nose", t:"鼻子", r:"bí zi", c:"Body"},
  {s:"Mouth", t:"嘴", r:"zuǐ", c:"Body"},
  {s:"Tooth", t:"牙齿", r:"yá chǐ", c:"Body"},
  {s:"Neck", t:"脖子", r:"bó zi", c:"Body"},
  {s:"Shoulder", t:"肩膀", r:"jiān bǎng", c:"Body"},
  {s:"Arm", t:"胳膊", r:"gē bo", c:"Body"},
  {s:"Hand", t:"手", r:"shǒu", c:"Body"},
  {s:"Finger", t:"手指", r:"shǒu zhǐ", c:"Body"},
  {s:"Chest", t:"胸", r:"xiōng", c:"Body"},
  {s:"Back", t:"背", r:"bèi", c:"Body"},
  {s:"Leg", t:"腿", r:"tuǐ", c:"Body"},
  {s:"Knee", t:"膝盖", r:"xī gài", c:"Body"},
  {s:"Foot", t:"脚", r:"jiǎo", c:"Body"},
  {s:"Heart", t:"心", r:"xīn", c:"Body"},
  {s:"Blood", t:"血", r:"xuè", c:"Body"},
  // Clothing
  {s:"Shirt", t:"衬衫", r:"chèn shān", c:"Clothing"},
  {s:"Pants", t:"裤子", r:"kù zi", c:"Clothing"},
  {s:"Jacket", t:"夹克", r:"jiā kè", c:"Clothing"},
  {s:"Coat", t:"外套", r:"wài tào", c:"Clothing"},
  {s:"Shoes", t:"鞋子", r:"xié zi", c:"Clothing"},
  {s:"Hat", t:"帽子", r:"mào zi", c:"Clothing"},
  {s:"Socks", t:"袜子", r:"wà zi", c:"Clothing"},
  {s:"Gloves", t:"手套", r:"shǒu tào", c:"Clothing"},
  {s:"Belt", t:"腰带", r:"yāo dài", c:"Clothing"},
  {s:"Watch", t:"手表", r:"shǒu biǎo", c:"Clothing"},
  {s:"Wallet", t:"钱包", r:"qián bāo", c:"Clothing"},
  {s:"Backpack", t:"背包", r:"bēi bāo", c:"Clothing"},
  // People
  {s:"Mother", t:"母亲", r:"mǔ qīn", c:"People"},
  {s:"Father", t:"父亲", r:"fù qīn", c:"People"},
  {s:"Sister", t:"姐妹", r:"jiě mèi", c:"People"},
  {s:"Brother", t:"兄弟", r:"xiōng dì", c:"People"},
  {s:"Daughter", t:"女儿", r:"nǚ ér", c:"People"},
  {s:"Son", t:"儿子", r:"ér zi", c:"People"},
  {s:"Wife", t:"妻子", r:"qī zi", c:"People"},
  {s:"Husband", t:"丈夫", r:"zhàng fu", c:"People"},
  {s:"Grandmother", t:"奶奶", r:"nǎi nai", c:"People"},
  {s:"Grandfather", t:"爷爷", r:"yé ye", c:"People"},
  {s:"Aunt", t:"阿姨", r:"ā yí", c:"People"},
  {s:"Uncle", t:"叔叔", r:"shū shu", c:"People"},
  {s:"Friend", t:"朋友", r:"péng yǒu", c:"People"},
  {s:"Teacher", t:"老师", r:"lǎo shī", c:"People"},
  {s:"Student", t:"学生", r:"xué shēng", c:"People"},
  {s:"Doctor", t:"医生", r:"yī shēng", c:"People"},
  {s:"Nurse", t:"护士", r:"hù shi", c:"People"},
  {s:"Baby", t:"宝宝", r:"bǎo bao", c:"People"},
  {s:"Child", t:"孩子", r:"hái zi", c:"People"},
  {s:"Man", t:"男人", r:"nán rén", c:"People"},
  {s:"Woman", t:"女人", r:"nǚ rén", c:"People"},
  {s:"Person", t:"人", r:"rén", c:"People"},
  {s:"Name", t:"名字", r:"míng zi", c:"People"},
  {s:"Family", t:"家庭", r:"jiā tíng", c:"People"},
  // Adjectives
  {s:"Big", t:"大", r:"dà", c:"Adjectives"},
  {s:"Small", t:"小", r:"xiǎo", c:"Adjectives"},
  {s:"Tall", t:"高", r:"gāo", c:"Adjectives"},
  {s:"Short", t:"矮", r:"ǎi", c:"Adjectives"},
  {s:"Long", t:"长", r:"cháng", c:"Adjectives"},
  {s:"Hot", t:"热", r:"rè", c:"Adjectives"},
  {s:"Cold", t:"冷", r:"lěng", c:"Adjectives"},
  {s:"Good", t:"好", r:"hǎo", c:"Adjectives"},
  {s:"Bad", t:"坏", r:"huài", c:"Adjectives"},
  {s:"Beautiful", t:"漂亮", r:"piào liang", c:"Adjectives"},
  {s:"Ugly", t:"丑", r:"chǒu", c:"Adjectives"},
  {s:"Rich", t:"有钱", r:"yǒu qián", c:"Adjectives"},
  {s:"Poor", t:"穷", r:"qióng", c:"Adjectives"},
  {s:"Young", t:"年轻", r:"nián qīng", c:"Adjectives"},
  {s:"Old", t:"老", r:"lǎo", c:"Adjectives"},
  {s:"New", t:"新", r:"xīn", c:"Adjectives"},
  {s:"Easy", t:"容易", r:"róng yì", c:"Adjectives"},
  {s:"Difficult", t:"难", r:"nán", c:"Adjectives"},
  {s:"Cheap", t:"便宜", r:"pián yi", c:"Adjectives"},
  {s:"Expensive", t:"贵", r:"guì", c:"Adjectives"},
  {s:"Clean", t:"干净", r:"gān jìng", c:"Adjectives"},
  {s:"Dirty", t:"脏", r:"zāng", c:"Adjectives"},
  {s:"Happy", t:"高兴", r:"gāo xìng", c:"Adjectives"},
  {s:"Sad", t:"难过", r:"nán guò", c:"Adjectives"},
  {s:"Angry", t:"生气", r:"shēng qì", c:"Adjectives"},
  {s:"Nervous", t:"紧张", r:"jǐn zhāng", c:"Adjectives"},
  {s:"Smart", t:"聪明", r:"cōng míng", c:"Adjectives"},
  {s:"Funny", t:"好笑", r:"hǎo xiào", c:"Adjectives"},
  {s:"Tired", t:"累", r:"lèi", c:"Adjectives"},
  {s:"Sick", t:"生病", r:"shēng bìng", c:"Adjectives"},
  {s:"Important", t:"重要", r:"zhòng yào", c:"Adjectives"},
  {s:"Free", t:"免费", r:"miǎn fèi", c:"Adjectives"},
  {s:"Busy", t:"忙", r:"máng", c:"Adjectives"},
  {s:"Same", t:"一样", r:"yí yàng", c:"Adjectives"},
  {s:"Different", t:"不同", r:"bù tóng", c:"Adjectives"},
  // Verbs
  {s:"To be", t:"是", r:"shì", c:"Verbs"},
  {s:"To have", t:"有", r:"yǒu", c:"Verbs"},
  {s:"To do", t:"做", r:"zuò", c:"Verbs"},
  {s:"To go", t:"去", r:"qù", c:"Verbs"},
  {s:"To come", t:"来", r:"lái", c:"Verbs"},
  {s:"To say", t:"说", r:"shuō", c:"Verbs"},
  {s:"To speak", t:"说话", r:"shuō huà", c:"Verbs"},
  {s:"To ask", t:"问", r:"wèn", c:"Verbs"},
  {s:"To answer", t:"回答", r:"huí dá", c:"Verbs"},
  {s:"To want", t:"要", r:"yào", c:"Verbs"},
  {s:"To need", t:"需要", r:"xū yào", c:"Verbs"},
  {s:"To like", t:"喜欢", r:"xǐ huān", c:"Verbs"},
  {s:"To love", t:"爱", r:"ài", c:"Verbs"},
  {s:"To hate", t:"恨", r:"hèn", c:"Verbs"},
  {s:"To know", t:"知道", r:"zhī dào", c:"Verbs"},
  {s:"To think", t:"想", r:"xiǎng", c:"Verbs"},
  {s:"To believe", t:"相信", r:"xiāng xìn", c:"Verbs"},
  {s:"To understand", t:"明白", r:"míng bai", c:"Verbs"},
  {s:"To learn", t:"学", r:"xué", c:"Verbs"},
  {s:"To teach", t:"教", r:"jiāo", c:"Verbs"},
  {s:"To study", t:"学习", r:"xué xí", c:"Verbs"},
  {s:"To read", t:"读", r:"dú", c:"Verbs"},
  {s:"To write", t:"写", r:"xiě", c:"Verbs"},
  {s:"To see", t:"看见", r:"kàn jiàn", c:"Verbs"},
  {s:"To watch", t:"看", r:"kàn", c:"Verbs"},
  {s:"To listen", t:"听", r:"tīng", c:"Verbs"},
  {s:"To walk", t:"走路", r:"zǒu lù", c:"Verbs"},
  {s:"To run", t:"跑", r:"pǎo", c:"Verbs"},
  {s:"To swim", t:"游泳", r:"yóu yǒng", c:"Verbs"},
  {s:"To travel", t:"旅行", r:"lǚ xíng", c:"Verbs"},
  {s:"To arrive", t:"到达", r:"dào dá", c:"Verbs"},
  {s:"To leave", t:"离开", r:"lí kāi", c:"Verbs"},
  {s:"To buy", t:"买", r:"mǎi", c:"Verbs"},
  {s:"To sell", t:"卖", r:"mài", c:"Verbs"},
  {s:"To give", t:"给", r:"gěi", c:"Verbs"},
  {s:"To take", t:"拿", r:"ná", c:"Verbs"},
  {s:"To find", t:"找到", r:"zhǎo dào", c:"Verbs"},
  {s:"To lose", t:"丢", r:"diū", c:"Verbs"},
  {s:"To wait", t:"等", r:"děng", c:"Verbs"},
  {s:"To open", t:"打开", r:"dǎ kāi", c:"Verbs"},
  {s:"To close", t:"关上", r:"guān shàng", c:"Verbs"},
  {s:"To start", t:"开始", r:"kāi shǐ", c:"Verbs"},
  {s:"To finish", t:"结束", r:"jié shù", c:"Verbs"},
  {s:"To work", t:"工作", r:"gōng zuò", c:"Verbs"},
  {s:"To sleep", t:"睡觉", r:"shuì jiào", c:"Verbs"},
  {s:"To wake up", t:"起床", r:"qǐ chuáng", c:"Verbs"},
  {s:"To laugh", t:"笑", r:"xiào", c:"Verbs"},
  {s:"To cry", t:"哭", r:"kū", c:"Verbs"},
  {s:"To sing", t:"唱歌", r:"chàng gē", c:"Verbs"},
  {s:"To dance", t:"跳舞", r:"tiào wǔ", c:"Verbs"},
  {s:"To play", t:"玩", r:"wán", c:"Verbs"},
  {s:"To help", t:"帮助", r:"bāng zhù", c:"Verbs"},
  {s:"To call", t:"打电话", r:"dǎ diàn huà", c:"Verbs"},
  {s:"To send", t:"发送", r:"fā sòng", c:"Verbs"},
  {s:"To forget", t:"忘记", r:"wàng jì", c:"Verbs"},
  {s:"To feel", t:"感觉", r:"gǎn jué", c:"Verbs"},
  {s:"To hope", t:"希望", r:"xī wàng", c:"Verbs"},
  // Time
  {s:"Time", t:"时间", r:"shí jiān", c:"Time"},
  {s:"Hour", t:"小时", r:"xiǎo shí", c:"Time"},
  {s:"Day", t:"天", r:"tiān", c:"Time"},
  {s:"Week", t:"星期", r:"xīng qī", c:"Time"},
  {s:"Month", t:"月", r:"yuè", c:"Time"},
  {s:"Year", t:"年", r:"nián", c:"Time"},
  {s:"Today", t:"今天", r:"jīn tiān", c:"Time"},
  {s:"Tomorrow", t:"明天", r:"míng tiān", c:"Time"},
  {s:"Yesterday", t:"昨天", r:"zuó tiān", c:"Time"},
  {s:"Morning", t:"早上", r:"zǎo shang", c:"Time"},
  {s:"Afternoon", t:"下午", r:"xià wǔ", c:"Time"},
  {s:"Evening", t:"晚上", r:"wǎn shang", c:"Time"},
  {s:"Now", t:"现在", r:"xiàn zài", c:"Time"},
  {s:"Early", t:"早", r:"zǎo", c:"Time"},
  {s:"Late", t:"晚", r:"wǎn", c:"Time"},
  {s:"Always", t:"总是", r:"zǒng shì", c:"Time"},
  {s:"Never", t:"从不", r:"cóng bù", c:"Time"},
  {s:"Sometimes", t:"有时候", r:"yǒu shí hou", c:"Time"},
  {s:"Already", t:"已经", r:"yǐ jīng", c:"Time"},
  {s:"Soon", t:"很快", r:"hěn kuài", c:"Time"},
  {s:"Monday", t:"星期一", r:"xīng qī yī", c:"Time"},
  {s:"Tuesday", t:"星期二", r:"xīng qī èr", c:"Time"},
  {s:"Wednesday", t:"星期三", r:"xīng qī sān", c:"Time"},
  {s:"Thursday", t:"星期四", r:"xīng qī sì", c:"Time"},
  {s:"Friday", t:"星期五", r:"xīng qī wǔ", c:"Time"},
  {s:"Saturday", t:"星期六", r:"xīng qī liù", c:"Time"},
  {s:"Sunday", t:"星期天", r:"xīng qī tiān", c:"Time"},
  // Home
  {s:"House", t:"房子", r:"fáng zi", c:"Home"},
  {s:"Room", t:"房间", r:"fáng jiān", c:"Home"},
  {s:"Door", t:"门", r:"mén", c:"Home"},
  {s:"Window", t:"窗户", r:"chuāng hu", c:"Home"},
  {s:"Bed", t:"床", r:"chuáng", c:"Home"},
  {s:"Table", t:"桌子", r:"zhuō zi", c:"Home"},
  {s:"Chair", t:"椅子", r:"yǐ zi", c:"Home"},
  {s:"Key", t:"钥匙", r:"yào shi", c:"Home"},
  {s:"Stairs", t:"楼梯", r:"lóu tī", c:"Home"},
  {s:"Garden", t:"花园", r:"huā yuán", c:"Home"},
  {s:"Kitchen", t:"厨房", r:"chú fáng", c:"Home"},
  {s:"Bathroom", t:"卫生间", r:"wèi shēng jiān", c:"Home"},
  // Travel
  {s:"Airport", t:"飞机场", r:"fēi jī chǎng", c:"Travel"},
  {s:"Train station", t:"火车站", r:"huǒ chē zhàn", c:"Travel"},
  {s:"Ticket", t:"票", r:"piào", c:"Travel"},
  {s:"Passport", t:"护照", r:"hù zhào", c:"Travel"},
  {s:"Luggage", t:"行李", r:"xíng li", c:"Travel"},
  {s:"Hotel", t:"酒店", r:"jiǔ diàn", c:"Travel"},
  {s:"Beach", t:"海滩", r:"hǎi tān", c:"Travel"},
  {s:"Mountain", t:"山", r:"shān", c:"Travel"},
  {s:"City", t:"城市", r:"chéng shì", c:"Travel"},
  {s:"Country", t:"国家", r:"guó jiā", c:"Travel"},
  {s:"Trip", t:"旅行", r:"lǚ xíng", c:"Travel"},
  {s:"Map", t:"地图", r:"dì tú", c:"Travel"},
  {s:"Airplane", t:"飞机", r:"fēi jī", c:"Travel"},
  {s:"Train", t:"火车", r:"huǒ chē", c:"Travel"},
  {s:"Bus", t:"公共汽车", r:"gōng gòng qì chē", c:"Travel"},
  {s:"Taxi", t:"出租车", r:"chū zū chē", c:"Travel"},
  {s:"Subway", t:"地铁", r:"dì tiě", c:"Travel"},
  {s:"Street", t:"街", r:"jiē", c:"Travel"},
  // Weather
  {s:"Weather", t:"天气", r:"tiān qì", c:"Weather"},
  {s:"Rain", t:"雨", r:"yǔ", c:"Weather"},
  {s:"Snow", t:"雪", r:"xuě", c:"Weather"},
  {s:"Wind", t:"风", r:"fēng", c:"Weather"},
  {s:"Sun", t:"太阳", r:"tài yáng", c:"Weather"},
  {s:"Cloud", t:"云", r:"yún", c:"Weather"},
  {s:"Sunny", t:"晴天", r:"qíng tiān", c:"Weather"},
  {s:"Cloudy", t:"多云", r:"duō yún", c:"Weather"},
  {s:"Rainy", t:"下雨", r:"xià yǔ", c:"Weather"},
  {s:"Snowy", t:"下雪", r:"xià xuě", c:"Weather"},
  {s:"Windy", t:"刮风", r:"guā fēng", c:"Weather"},
  {s:"Warm", t:"暖和", r:"nuǎn huo", c:"Weather"},
  {s:"Cold", t:"冷", r:"lěng", c:"Weather"},
  // Nature
  {s:"Tree", t:"树", r:"shù", c:"Nature"},
  {s:"Flower", t:"花", r:"huā", c:"Nature"},
  {s:"Forest", t:"森林", r:"sēn lín", c:"Nature"},
  {s:"River", t:"河", r:"hé", c:"Nature"},
  {s:"Lake", t:"湖", r:"hú", c:"Nature"},
  {s:"Ocean", t:"大海", r:"dà hǎi", c:"Nature"},
  {s:"Sky", t:"天空", r:"tiān kōng", c:"Nature"},
  {s:"Star", t:"星星", r:"xīng xīng", c:"Nature"},
  {s:"Moon", t:"月亮", r:"yuè liang", c:"Nature"},
  {s:"Earth", t:"地球", r:"dì qiú", c:"Nature"},
  {s:"Fire", t:"火", r:"huǒ", c:"Nature"},
  {s:"Air", t:"空气", r:"kōng qì", c:"Nature"},
  {s:"Rock", t:"石头", r:"shí tou", c:"Nature"},
  {s:"Sand", t:"沙子", r:"shā zi", c:"Nature"},
  {s:"Island", t:"岛", r:"dǎo", c:"Nature"},
  {s:"Desert", t:"沙漠", r:"shā mò", c:"Nature"},
  // Occupations
  {s:"Engineer", t:"工程师", r:"gōng chéng shī", c:"Occupations"},
  {s:"Lawyer", t:"律师", r:"lǜ shī", c:"Occupations"},
  {s:"Journalist", t:"记者", r:"jì zhě", c:"Occupations"},
  {s:"Pilot", t:"飞行员", r:"fēi xíng yuán", c:"Occupations"},
  {s:"Police", t:"警察", r:"jǐng chá", c:"Occupations"},
  {s:"Farmer", t:"农民", r:"nóng mín", c:"Occupations"},
  {s:"Chef", t:"厨师", r:"chú shī", c:"Occupations"},
  {s:"Artist", t:"艺术家", r:"yì shù jiā", c:"Occupations"},
  {s:"Writer", t:"作家", r:"zuò jiā", c:"Occupations"},
  {s:"Scientist", t:"科学家", r:"kē xué jiā", c:"Occupations"},
  {s:"Programmer", t:"程序员", r:"chéng xù yuán", c:"Occupations"},
  {s:"Soldier", t:"士兵", r:"shì bīng", c:"Occupations"},
  // Useful Words
  {s:"In", t:"在...里", r:"zài...lǐ", c:"Useful Words"},
  {s:"On", t:"在...上", r:"zài...shàng", c:"Useful Words"},
  {s:"Under", t:"在...下", r:"zài...xià", c:"Useful Words"},
  {s:"With", t:"跟", r:"gēn", c:"Useful Words"},
  {s:"Without", t:"没有", r:"méi yǒu", c:"Useful Words"},
  {s:"For", t:"为了", r:"wèi le", c:"Useful Words"},
  {s:"From", t:"从", r:"cóng", c:"Useful Words"},
  {s:"To", t:"到", r:"dào", c:"Useful Words"},
  {s:"Here", t:"这里", r:"zhè lǐ", c:"Useful Words"},
  {s:"There", t:"那里", r:"nà lǐ", c:"Useful Words"},
  {s:"Where", t:"哪里", r:"nǎ lǐ", c:"Useful Words"},
  {s:"When", t:"什么时候", r:"shén me shí hou", c:"Useful Words"},
  {s:"Why", t:"为什么", r:"wèi shén me", c:"Useful Words"},
  {s:"How", t:"怎么", r:"zěn me", c:"Useful Words"},
  {s:"Who", t:"谁", r:"shuí", c:"Useful Words"},
  {s:"What", t:"什么", r:"shén me", c:"Useful Words"},
  {s:"This", t:"这个", r:"zhè gè", c:"Useful Words"},
  {s:"That", t:"那个", r:"nà gè", c:"Useful Words"},
  {s:"Some", t:"一些", r:"yī xiē", c:"Useful Words"},
  {s:"All", t:"所有", r:"suǒ yǒu", c:"Useful Words"},
  {s:"Many", t:"很多", r:"hěn duō", c:"Useful Words"},
  {s:"More", t:"更多", r:"gèng duō", c:"Useful Words"},
  {s:"Very", t:"很", r:"hěn", c:"Useful Words"},
  {s:"Also", t:"也", r:"yě", c:"Useful Words"},
  {s:"But", t:"但是", r:"dàn shì", c:"Useful Words"},
  {s:"And", t:"和", r:"hé", c:"Useful Words"},
  {s:"Or", t:"或者", r:"huò zhě", c:"Useful Words"},
  {s:"Because", t:"因为", r:"yīn wèi", c:"Useful Words"},
  {s:"If", t:"如果", r:"rú guǒ", c:"Useful Words"},
  {s:"Not", t:"不", r:"bù", c:"Useful Words"},
]

const zhSentences = [
  {s:"Hello, how are you?", t:"你好，你好吗？", r:"nǐ hǎo, nǐ hǎo ma"},
  {s:"I am fine, thank you.", t:"我很好，谢谢。", r:"wǒ hěn hǎo, xiè xiè"},
  {s:"What is your name?", t:"你叫什么名字？", r:"nǐ jiào shén me míng zì"},
  {s:"My name is Wang Ming.", t:"我叫王明。", r:"wǒ jiào wáng míng"},
  {s:"Nice to meet you.", t:"很高兴认识你。", r:"hěn gāo xìng rèn shí nǐ"},
  {s:"Where are you from?", t:"你是哪里人？", r:"nǐ shì nǎ lǐ rén"},
  {s:"I am from China.", t:"我是中国人。", r:"wǒ shì zhōng guó rén"},
  {s:"How old are you?", t:"你多大了？", r:"nǐ duō dà le"},
  {s:"I am twenty-five years old.", t:"我二十五岁。", r:"wǒ èr shí wǔ suì"},
  {s:"Do you speak Chinese?", t:"你会说中文吗？", r:"nǐ huì shuō zhōng wén ma"},
  {s:"I speak a little Chinese.", t:"我会说一点中文。", r:"wǒ huì shuō yī diǎn zhōng wén"},
  {s:"I am a student.", t:"我是学生。", r:"wǒ shì xué shēng"},
  {s:"Where do you live?", t:"你住在哪里？", r:"nǐ zhù zài nǎ lǐ"},
  {s:"I live in Beijing.", t:"我住在北京。", r:"wǒ zhù zài běi jīng"},
  {s:"Do you have siblings?", t:"你有兄弟姐妹吗？", r:"nǐ yǒu xiōng dì jiě mèi ma"},
  {s:"I have one older brother.", t:"我有一个哥哥。", r:"wǒ yǒu yī gè gē ge"},
  {s:"What time is it?", t:"几点了？", r:"jǐ diǎn le"},
  {s:"It is two o'clock.", t:"两点。", r:"liǎng diǎn"},
  {s:"Today is Monday.", t:"今天是星期一。", r:"jīn tiān shì xīng qī yī"},
  {s:"How is the weather?", t:"天气怎么样？", r:"tiān qì zěn me yàng"},
  {s:"It is sunny and warm.", t:"今天晴天，很暖和。", r:"jīn tiān qíng tiān, hěn nuǎn huo"},
  {s:"It is raining heavily.", t:"正在下大雨。", r:"zhèng zài xià dà yǔ"},
  {s:"Where is the bathroom?", t:"卫生间在哪里？", r:"wèi shēng jiān zài nǎ lǐ"},
  {s:"The restaurant is on the corner.", t:"餐厅在拐角处。", r:"cān tīng zài guǎi jiǎo chù"},
  {s:"How much does it cost?", t:"多少钱？", r:"duō shao qián"},
  {s:"It costs ten dollars.", t:"十美元。", r:"shí měi yuán"},
  {s:"I would like a coffee, please.", t:"请给我一杯咖啡。", r:"qǐng gěi wǒ yī bēi kā fēi"},
  {s:"The food is delicious.", t:"食物很好吃。", r:"shí wù hěn hǎo chī"},
  {s:"Can I have the bill?", t:"请给我账单。", r:"qǐng gěi wǒ zhàng dān"},
  {s:"Where is the supermarket?", t:"超市在哪里？", r:"chāo shì zài nǎ lǐ"},
  {s:"Turn left at the corner.", t:"在拐角向左转。", r:"zài guǎi jiǎo xiàng zuǒ zhuǎn"},
  {s:"Go straight ahead.", t:"一直往前走。", r:"yī zhí wǎng qián zǒu"},
  {s:"The museum is far from here.", t:"博物馆离这里很远。", r:"bó wù guǎn lí zhè lǐ hěn yuǎn"},
  {s:"I am going to the beach tomorrow.", t:"我明天去海滩。", r:"wǒ míng tiān qù hǎi tān"},
  {s:"I love to read books.", t:"我爱看书。", r:"wǒ ài kàn shū"},
  {s:"She is very intelligent.", t:"她很聪明。", r:"tā hěn cōng míng"},
  {s:"He is a good friend.", t:"他是一个好朋友。", r:"tā shì yī gè hǎo péng yǒu"},
  {s:"I have to work tomorrow.", t:"我明天要工作。", r:"wǒ míng tiān yào gōng zuò"},
  {s:"She studies at university.", t:"她在大学学习。", r:"tā zài dà xué xué xí"},
  {s:"He runs every morning.", t:"他每天早上跑步。", r:"tā měi tiān zǎo shang pǎo bù"},
  {s:"We are learning Chinese.", t:"我们在学中文。", r:"wǒ men zài xué zhōng wén"},
  {s:"Can you help me?", t:"你能帮我吗？", r:"nǐ néng bāng wǒ ma"},
  {s:"I don't understand.", t:"我不明白。", r:"wǒ bù míng bai"},
  {s:"Can you repeat that?", t:"你能重复一遍吗？", r:"nǐ néng chóng fù yī biàn ma"},
  {s:"Please speak more slowly.", t:"请说慢一点。", r:"qǐng shuō màn yī diǎn"},
  {s:"I am lost.", t:"我迷路了。", r:"wǒ mí lù le"},
  {s:"I need a doctor.", t:"我需要医生。", r:"wǒ xū yào yī shēng"},
  {s:"I have a headache.", t:"我头痛。", r:"wǒ tóu tòng"},
  {s:"I am tired.", t:"我累了。", r:"wǒ lèi le"},
  {s:"I am hungry.", t:"我饿了。", r:"wǒ è le"},
  {s:"I am thirsty.", t:"我渴了。", r:"wǒ kě le"},
  {s:"What do you want to eat?", t:"你想吃什么？", r:"nǐ xiǎng chī shén me"},
  {s:"I want to eat rice.", t:"我想吃饭。", r:"wǒ xiǎng chī fàn"},
  {s:"This is very tasty.", t:"这个很好吃。", r:"zhè gè hěn hǎo chī"},
  {s:"Happy birthday!", t:"生日快乐！", r:"shēng rì kuài lè"},
  {s:"Merry Christmas!", t:"圣诞快乐！", r:"shèng dàn kuài lè"},
  {s:"Happy New Year!", t:"新年快乐！", r:"xīn nián kuài lè"},
  {s:"Congratulations!", t:"恭喜！", r:"gōng xǐ"},
  {s:"I miss you.", t:"我想你。", r:"wǒ xiǎng nǐ"},
  {s:"I love you.", t:"我爱你。", r:"wǒ ài nǐ"},
  {s:"I am sorry.", t:"对不起。", r:"duì bu qǐ"},
  {s:"Don't worry.", t:"别担心。", r:"bié dān xīn"},
  {s:"It doesn't matter.", t:"没关系。", r:"méi guān xì"},
  {s:"See you later!", t:"回头见！", r:"huí tóu jiàn"},
  {s:"Take care!", t:"保重！", r:"bǎo zhòng"},
  {s:"I will call you tonight.", t:"我今晚给你打电话。", r:"wǒ jīn wǎn gěi nǐ dǎ diàn huà"},
  {s:"The movie starts at eight.", t:"电影八点开始。", r:"diàn yǐng bā diǎn kāi shǐ"},
  {s:"Do you want to dance?", t:"你想跳舞吗？", r:"nǐ xiǎng tiào wǔ ma"},
  {s:"I like this music.", t:"我喜欢这个音乐。", r:"wǒ xǐ huān zhè gè yīn yuè"},
  {s:"I need to charge my phone.", t:"我需要给手机充电。", r:"wǒ xū yào gěi shǒu jī chōng diàn"},
  {s:"The hotel is very nice.", t:"酒店很好。", r:"jiǔ diàn hěn hǎo"},
  {s:"I lost my passport.", t:"我丢了护照。", r:"wǒ diū le hù zhào"},
  {s:"I am here on vacation.", t:"我来这里度假。", r:"wǒ lái zhè lǐ dù jià"},
  {s:"Is breakfast included?", t:"包括早餐吗？", r:"bāo kuò zǎo cān ma"},
  {s:"I need to exchange money.", t:"我需要换钱。", r:"wǒ xū yào huàn qián"},
  {s:"I don't have cash.", t:"我没有现金。", r:"wǒ méi yǒu xiàn jīn"},
  {s:"This is too expensive.", t:"这个太贵了。", r:"zhè gè tài guì le"},
  {s:"She is my best friend.", t:"她是我最好的朋友。", r:"tā shì wǒ zuì hǎo de péng yǒu"},
  {s:"My mother is a doctor.", t:"我妈妈是医生。", r:"wǒ mā ma shì yī shēng"},
  {s:"I have two cats and a dog.", t:"我有两只猫和一只狗。", r:"wǒ yǒu liǎng zhī māo hé yī zhī gǒu"},
  {s:"I live in a small apartment.", t:"我住在一个小公寓。", r:"wǒ zhù zài yī gè xiǎo gōng yù"},
  {s:"I wake up at seven every day.", t:"我每天七点起床。", r:"wǒ měi tiān qī diǎn qǐ chuáng"},
  {s:"I go to work by bus.", t:"我坐公共汽车上班。", r:"wǒ zuò gōng gòng qì chē shàng bān"},
  {s:"I go to bed at eleven.", t:"我十一点睡觉。", r:"wǒ shí yī diǎn shuì jiào"},
  {s:"What did you do yesterday?", t:"你昨天做了什么？", r:"nǐ zuó tiān zuò le shén me"},
  {s:"I went to the cinema.", t:"我去看电影了。", r:"wǒ qù kàn diàn yǐng le"},
  {s:"I read an interesting book.", t:"我看了一本有趣的书。", r:"wǒ kàn le yī běn yǒu qù de shū"},
  {s:"I visited my grandmother.", t:"我去看奶奶了。", r:"wǒ qù kàn nǎi nai le"},
  {s:"Tomorrow I will go to the beach.", t:"明天我要去海滩。", r:"míng tiān wǒ yào qù hǎi tān"},
  {s:"I want to travel to China.", t:"我想去中国旅行。", r:"wǒ xiǎng qù zhōng guó lǚ xíng"},
  {s:"I am learning Chinese.", t:"我在学中文。", r:"wǒ zài xué zhōng wén"},
  {s:"You look great today!", t:"你今天看起来很棒！", r:"nǐ jīn tiān kàn qǐ lái hěn bàng"},
  {s:"I need to exercise more.", t:"我需要多运动。", r:"wǒ xū yào duō yùn dòng"},
  {s:"The park is very quiet.", t:"公园很安静。", r:"gōng yuán hěn ān jìng"},
  {s:"Beijing is a beautiful city.", t:"北京是一个美丽的城市。", r:"běi jīng shì yī gè měi lì de chéng shì"},
  {s:"The weather is perfect today.", t:"今天天气很好。", r:"jīn tiān tiān qì hěn hǎo"},
  {s:"Summer is my favorite season.", t:"夏天是我最喜欢的季节。", r:"xià tiān shì wǒ zuì xǐ huān de jì jié"},
  {s:"Can you open the window?", t:"你能打开窗户吗？", r:"nǐ néng dǎ kāi chuāng hu ma"},
  {s:"Please close the door.", t:"请关上门。", r:"qǐng guān shàng mén"},
  {s:"Sit down, please.", t:"请坐。", r:"qǐng zuò"},
  {s:"Be quiet, please.", t:"请安静。", r:"qǐng ān jìng"},
  {s:"Hurry up!", t:"快点！", r:"kuài diǎn"},
  {s:"Wait for me!", t:"等等我！", r:"děng děng wǒ"},
  {s:"Follow me.", t:"跟我来。", r:"gēn wǒ lái"},
  {s:"Let's take a walk.", t:"我们去散步吧。", r:"wǒ men qù sàn bù ba"},
  {s:"The children are playing outside.", t:"孩子们在外面玩。", r:"hái zi men zài wài miàn wán"},
  {s:"I feel happy today.", t:"我今天很开心。", r:"wǒ jīn tiān hěn kāi xīn"},
  {s:"Why are you sad?", t:"你为什么难过？", r:"nǐ wèi shén me nán guò"},
  {s:"Don't be afraid.", t:"不要害怕。", r:"bú yào hài pà"},
  {s:"Everything will be fine.", t:"一切都会好的。", r:"yī qiè dōu huì hǎo de"},
  {s:"I believe in you.", t:"我相信你。", r:"wǒ xiāng xìn nǐ"},
  {s:"Thank you for everything.", t:"感谢你的一切。", r:"gǎn xiè nǐ de yī qiè"},
  {s:"I agree with you.", t:"我同意你的看法。", r:"wǒ tóng yì nǐ de kàn fǎ"},
  {s:"That is a good idea.", t:"这是个好主意。", r:"zhè shì gè hǎo zhǔ yì"},
  {s:"Are you ready?", t:"你准备好了吗？", r:"nǐ zhǔn bèi hǎo le ma"},
  {s:"Don't forget your keys.", t:"别忘了你的钥匙。", r:"bié wàng le nǐ de yào shi"},
  {s:"The internet is very slow.", t:"网速很慢。", r:"wǎng sù hěn màn"},
  {s:"I will send you the document.", t:"我会给你发文件。", r:"wǒ huì gěi nǐ fā wén jiàn"},
  {s:"Happy weekend!", t:"周末快乐！", r:"zhōu mò kuài lè"},
  {s:"What are your plans for today?", t:"你今天有什么计划？", r:"nǐ jīn tiān yǒu shén me jì huà"},
  {s:"I have nothing planned.", t:"我没什么计划。", r:"wǒ méi shén me jì huà"},
  {s:"The soup is very hot.", t:"汤很烫。", r:"tāng hěn tàng"},
  {s:"Be careful, it's hot.", t:"小心，很烫。", r:"xiǎo xīn, hěn tàng"},
  {s:"Please pass me the salt.", t:"请把盐递给我。", r:"qǐng bǎ yán dì gěi wǒ"},
  {s:"Fruit is good for your health.", t:"水果对你的健康好。", r:"shuǐ guǒ duì nǐ de jiàn kāng hǎo"},
  {s:"I drink water every day.", t:"我每天喝水。", r:"wǒ měi tiān hē shuǐ"},
  {s:"This coffee is delicious.", t:"这咖啡很好喝。", r:"zhè kā fēi hěn hǎo hē"},
  {s:"The baby is crying.", t:"宝宝在哭。", r:"bǎo bao zài kū"},
  {s:"I like to spend time with my family.", t:"我喜欢和家人在一起。", r:"wǒ xǐ huān hé jiā rén zài yī qǐ"},
  {s:"Traveling is my passion.", t:"旅行是我的爱好。", r:"lǚ xíng shì wǒ de ài hào"},
  {s:"I have visited many countries.", t:"我去过很多国家。", r:"wǒ qù guò hěn duō guó jiā"},
  {s:"We need to protect the environment.", t:"我们需要保护环境。", r:"wǒ men xū yào bǎo hù huán jìng"},
  {s:"The river is polluted.", t:"河水被污染了。", r:"hé shuǐ bèi wū rǎn le"},
  {s:"We should plant more trees.", t:"我们应该种更多的树。", r:"wǒ men yīng gāi zhòng gèng duō de shù"},
  {s:"My dream is to travel around the world.", t:"我的梦想是环游世界。", r:"wǒ de mèng xiǎng shì huán yóu shì jiè"},
  {s:"I need to book a flight.", t:"我需要预订机票。", r:"wǒ xū yào yù dìng jī piào"},
  {s:"I prefer window seats on planes.", t:"我更喜欢靠窗的座位。", r:"wǒ gèng xǐ huān kào chuāng de zuò wèi"},
  {s:"I arrived safely at my destination.", t:"我安全到达了目的地。", r:"wǒ ān quán dào dá le mù dì dì"},
  {s:"I like my job.", t:"我喜欢我的工作。", r:"wǒ xǐ huān wǒ de gōng zuò"},
  {s:"I am looking for a new job.", t:"我在找新工作。", r:"wǒ zài zhǎo xīn gōng zuò"},
  {s:"I have an interview tomorrow.", t:"我明天有个面试。", r:"wǒ míng tiān yǒu gè miàn shì"},
  {s:"Can you recommend a good restaurant?", t:"你能推荐一个好餐厅吗？", r:"nǐ néng tuī jiàn yī gè hǎo cān tīng ma"},
  {s:"I am allergic to peanuts.", t:"我对花生过敏。", r:"wǒ duì huā shēng guò mǐn"},
  {s:"The bed is very comfortable.", t:"床很舒服。", r:"chuáng hěn shū fu"},
  {s:"I had a good night's sleep.", t:"我睡得很好。", r:"wǒ shuì de hěn hǎo"},
  {s:"I woke up early this morning.", t:"我今天早上醒得很早。", r:"wǒ jīn tiān zǎo shang xǐng de hěn zǎo"},
  {s:"I can see the mountains from here.", t:"我从这里可以看到山。", r:"wǒ cóng zhè lǐ kě yǐ kàn dào shān"},
  {s:"The local market is colorful and lively.", t:"当地市场色彩缤纷，很热闹。", r:"dāng dì shì chǎng sè cǎi bīn fēn, hěn rè nào"},
  {s:"I took many photos.", t:"我拍了很多照片。", r:"wǒ pāi le hěn duō zhào piàn"},
  {s:"I will remember this trip forever.", t:"我会永远记住这次旅行。", r:"wǒ huì yǒng yuǎn jì zhù zhè cì lǚ xíng"},
  {s:"I want to come back again.", t:"我想再来一次。", r:"wǒ xiǎng zài lái yī cì"},
  {s:"I feel relaxed and happy.", t:"我感到放松和快乐。", r:"wǒ gǎn dào fàng sōng hé kuài lè"},
  {s:"I am planning my next trip.", t:"我在计划下一次旅行。", r:"wǒ zài jì huà xià yī cì lǚ xíng"},
]

// ─── Arabic ──────────────────────────────────────────────────────────
const arWords = [
  {s:"Hello", t:"السلام عليكم", r:"as-salamu alaykum", c:"Greetings"},
  {s:"Good morning", t:"صباح الخير", r:"sabah al-khayr", c:"Greetings"},
  {s:"Good evening", t:"مساء الخير", r:"masa' al-khayr", c:"Greetings"},
  {s:"Goodbye", t:"مع السلامة", r:"ma'a as-salama", c:"Greetings"},
  {s:"See you later", t:"أراك لاحقاً", r:"araka lahiqan", c:"Greetings"},
  {s:"Thank you", t:"شكراً", r:"shukran", c:"Greetings"},
  {s:"Thanks a lot", t:"شكراً جزيلاً", r:"shukran jazeelan", c:"Greetings"},
  {s:"You're welcome", t:"عفواً", r:"afwan", c:"Greetings"},
  {s:"Please", t:"من فضلك", r:"min fadlik", c:"Greetings"},
  {s:"Excuse me", t:"عذراً", r:"udhran", c:"Greetings"},
  {s:"Sorry", t:"آسف", r:"asif", c:"Greetings"},
  {s:"How are you?", t:"كيف حالك", r:"kayfa haluk", c:"Greetings"},
  {s:"I'm fine", t:"أنا بخير", r:"ana bikhayr", c:"Greetings"},
  {s:"Nice to meet you", t:"تشرفنا", r:"tasharrafna", c:"Greetings"},
  {s:"Welcome", t:"أهلاً وسهلاً", r:"ahlan wa sahlan", c:"Greetings"},
  {s:"Cheers", t:"في صحتك", r:"fi sihhatik", c:"Greetings"},
  {s:"Good luck", t:"بالتوفيق", r:"bil tawfiq", c:"Greetings"},
  {s:"Take care", t:"اعتني بنفسك", r:"i'tani binafsik", c:"Greetings"},
  {s:"Long time no see", t:"لم أراك منذ زمن", r:"lam arak mundhu zaman", c:"Greetings"},
  {s:"What's up?", t:"ما الأخبار", r:"ma al-akhbar", c:"Greetings"},
  // Numbers
  {s:"Zero", t:"صفر", r:"sifr", c:"Numbers"},
  {s:"One", t:"واحد", r:"wahid", c:"Numbers"},
  {s:"Two", t:"اثنان", r:"ithnan", c:"Numbers"},
  {s:"Three", t:"ثلاثة", r:"thalatha", c:"Numbers"},
  {s:"Four", t:"أربعة", r:"arba'a", c:"Numbers"},
  {s:"Five", t:"خمسة", r:"khamsa", c:"Numbers"},
  {s:"Six", t:"ستة", r:"sitta", c:"Numbers"},
  {s:"Seven", t:"سبعة", r:"sab'a", c:"Numbers"},
  {s:"Eight", t:"ثمانية", r:"thamaniya", c:"Numbers"},
  {s:"Nine", t:"تسعة", r:"tis'a", c:"Numbers"},
  {s:"Ten", t:"عشرة", r:"ashara", c:"Numbers"},
  {s:"Twenty", t:"عشرون", r:"ishrun", c:"Numbers"},
  {s:"Thirty", t:"ثلاثون", r:"thalathun", c:"Numbers"},
  {s:"Hundred", t:"مئة", r:"mi'a", c:"Numbers"},
  {s:"Thousand", t:"ألف", r:"alf", c:"Numbers"},
  // Colors
  {s:"Red", t:"أحمر", r:"ahmar", c:"Colors"},
  {s:"Blue", t:"أزرق", r:"azraq", c:"Colors"},
  {s:"Green", t:"أخضر", r:"akhdar", c:"Colors"},
  {s:"Yellow", t:"أصفر", r:"asfar", c:"Colors"},
  {s:"Black", t:"أسود", r:"aswad", c:"Colors"},
  {s:"White", t:"أبيض", r:"abyad", c:"Colors"},
  {s:"Brown", t:"بني", r:"bunni", c:"Colors"},
  {s:"Orange", t:"برتقالي", r:"burtuqali", c:"Colors"},
  {s:"Pink", t:"وردي", r:"wardi", c:"Colors"},
  {s:"Purple", t:"أرجواني", r:"urjuwani", c:"Colors"},
  {s:"Gold", t:"ذهبي", r:"dhahabi", c:"Colors"},
  // Food
  {s:"Water", t:"ماء", r:"ma'", c:"Food & Drink"},
  {s:"Coffee", t:"قهوة", r:"qahwa", c:"Food & Drink"},
  {s:"Tea", t:"شاي", r:"shay", c:"Food & Drink"},
  {s:"Milk", t:"حليب", r:"halib", c:"Food & Drink"},
  {s:"Juice", t:"عصير", r:"asir", c:"Food & Drink"},
  {s:"Rice", t:"أرز", r:"aruzz", c:"Food & Drink"},
  {s:"Bread", t:"خبز", r:"khubz", c:"Food & Drink"},
  {s:"Chicken", t:"دجاج", r:"dajaj", c:"Food & Drink"},
  {s:"Meat", t:"لحم", r:"lahm", c:"Food & Drink"},
  {s:"Fish", t:"سمك", r:"samak", c:"Food & Drink"},
  {s:"Egg", t:"بيض", r:"bayd", c:"Food & Drink"},
  {s:"Cheese", t:"جبن", r:"jubn", c:"Food & Drink"},
  {s:"Soup", t:"شوربة", r:"shurba", c:"Food & Drink"},
  {s:"Fruit", t:"فاكهة", r:"fakiha", c:"Food & Drink"},
  {s:"Apple", t:"تفاح", r:"tuffah", c:"Food & Drink"},
  {s:"Banana", t:"موز", r:"mawz", c:"Food & Drink"},
  {s:"Orange", t:"برتقال", r:"burtuqal", c:"Food & Drink"},
  {s:"Grape", t:"عنب", r:"inab", c:"Food & Drink"},
  {s:"Strawberry", t:"فراولة", r:"farawla", c:"Food & Drink"},
  {s:"Tomato", t:"طماطم", r:"tamatim", c:"Food & Drink"},
  {s:"Potato", t:"بطاطس", r:"batatis", c:"Food & Drink"},
  {s:"Onion", t:"بصل", r:"basal", c:"Food & Drink"},
  {s:"Salt", t:"ملح", r:"milh", c:"Food & Drink"},
  {s:"Sugar", t:"سكر", r:"sukkar", c:"Food & Drink"},
  {s:"Honey", t:"عسل", r:"asal", c:"Food & Drink"},
  {s:"Chocolate", t:"شوكولاتة", r:"shukulata", c:"Food & Drink"},
  {s:"Cake", t:"كعكة", r:"ka'ka", c:"Food & Drink"},
  {s:"Breakfast", t:"فطور", r:"futur", c:"Food & Drink"},
  {s:"Lunch", t:"غداء", r:"ghada'", c:"Food & Drink"},
  {s:"Dinner", t:"عشاء", r:"asha'", c:"Food & Drink"},
  {s:"Restaurant", t:"مطعم", r:"mat'am", c:"Food & Drink"},
  {s:"Hungry", t:"جائع", r:"jai'", c:"Food & Drink"},
  {s:"Thirsty", t:"عطشان", r:"atshan", c:"Food & Drink"},
  {s:"Delicious", t:"لذيذ", r:"ladhidh", c:"Food & Drink"},
  {s:"To eat", t:"أكل", r:"akala", c:"Food & Drink"},
  {s:"To drink", t:"شرب", r:"shariba", c:"Food & Drink"},
  // Animals
  {s:"Dog", t:"كلب", r:"kalb", c:"Animals"},
  {s:"Cat", t:"قط", r:"qitt", c:"Animals"},
  {s:"Bird", t:"طائر", r:"ta'ir", c:"Animals"},
  {s:"Horse", t:"حصان", r:"hisan", c:"Animals"},
  {s:"Cow", t:"بقرة", r:"baqara", c:"Animals"},
  {s:"Sheep", t:"خروف", r:"kharuf", c:"Animals"},
  {s:"Lion", t:"أسد", r:"asad", c:"Animals"},
  {s:"Camel", t:"جمل", r:"jamal", c:"Animals"},
  {s:"Fish", t:"سمكة", r:"samaka", c:"Animals"},
  {s:"Elephant", t:"فيل", r:"fil", c:"Animals"},
  {s:"Rabbit", t:"أرنب", r:"arnab", c:"Animals"},
  {s:"Fox", t:"ثعلب", r:"tha'lab", c:"Animals"},
  {s:"Wolf", t:"ذئب", r:"dhi'b", c:"Animals"},
  {s:"Bear", t:"دب", r:"dubb", c:"Animals"},
  {s:"Monkey", t:"قرد", r:"qird", c:"Animals"},
  {s:"Snake", t:"ثعبان", r:"thu'ban", c:"Animals"},
  {s:"Turtle", t:"سلحفاة", r:"sulahfa", c:"Animals"},
  {s:"Eagle", t:"نسر", r:"nasr", c:"Animals"},
  {s:"Butterfly", t:"فراشة", r:"farasha", c:"Animals"},
  {s:"Bee", t:"نحلة", r:"ahla", c:"Animals"},
  // Body
  {s:"Head", t:"رأس", r:"ra's", c:"Body"},
  {s:"Hair", t:"شعر", r:"sha'r", c:"Body"},
  {s:"Face", t:"وجه", r:"wajh", c:"Body"},
  {s:"Eye", t:"عين", r:"ayn", c:"Body"},
  {s:"Ear", t:"أذن", r:"udhun", c:"Body"},
  {s:"Nose", t:"أنف", r:"anf", c:"Body"},
  {s:"Mouth", t:"فم", r:"fam", c:"Body"},
  {s:"Tooth", t:"سن", r:"sinn", c:"Body"},
  {s:"Hand", t:"يد", r:"yad", c:"Body"},
  {s:"Foot", t:"قدم", r:"qadam", c:"Body"},
  {s:"Heart", t:"قلب", r:"qalb", c:"Body"},
  {s:"Blood", t:"دم", r:"dam", c:"Body"},
  {s:"Arm", t:"ذراع", r:"dhira'", c:"Body"},
  {s:"Leg", t:"ساق", r:"saq", c:"Body"},
  // People
  {s:"Mother", t:"أم", r:"umm", c:"People"},
  {s:"Father", t:"أب", r:"ab", c:"People"},
  {s:"Sister", t:"أخت", r:"ukht", c:"People"},
  {s:"Brother", t:"أخ", r:"akh", c:"People"},
  {s:"Daughter", t:"ابنة", r:"ibna", c:"People"},
  {s:"Son", t:"ابن", r:"ibn", c:"People"},
  {s:"Wife", t:"زوجة", r:"zawja", c:"People"},
  {s:"Husband", t:"زوج", r:"zawj", c:"People"},
  {s:"Grandmother", t:"جدة", r:"jadda", c:"People"},
  {s:"Grandfather", t:"جد", r:"jadd", c:"People"},
  {s:"Uncle", t:"عم", r:"amm", c:"People"},
  {s:"Aunt", t:"خالة", r:"khala", c:"People"},
  {s:"Friend", t:"صديق", r:"sadiq", c:"People"},
  {s:"Teacher", t:"معلم", r:"mu'allim", c:"People"},
  {s:"Student", t:"طالب", r:"talib", c:"People"},
  {s:"Doctor", t:"طبيب", r:"tabib", c:"People"},
  {s:"Baby", t:"طفل", r:"tifl", c:"People"},
  {s:"Child", t:"ولد", r:"walad", c:"People"},
  {s:"Man", t:"رجل", r:"rajul", c:"People"},
  {s:"Woman", t:"امرأة", r:"imra'a", c:"People"},
  {s:"Person", t:"شخص", r:"shakhs", c:"People"},
  {s:"Family", t:"عائلة", r:"a'ila", c:"People"},
  {s:"Name", t:"اسم", r:"ism", c:"People"},
  // Adjectives
  {s:"Big", t:"كبير", r:"kabir", c:"Adjectives"},
  {s:"Small", t:"صغير", r:"saghir", c:"Adjectives"},
  {s:"Tall", t:"طويل", r:"tawil", c:"Adjectives"},
  {s:"Short", t:"قصير", r:"qasir", c:"Adjectives"},
  {s:"Long", t:"طويل", r:"tawil", c:"Adjectives"},
  {s:"Hot", t:"حار", r:"har", c:"Adjectives"},
  {s:"Cold", t:"بارد", r:"barid", c:"Adjectives"},
  {s:"Good", t:"جيد", r:"jayyid", c:"Adjectives"},
  {s:"Bad", t:"سيء", r:"sayyi'", c:"Adjectives"},
  {s:"Beautiful", t:"جميل", r:"jamil", c:"Adjectives"},
  {s:"Rich", t:"غني", r:"ghani", c:"Adjectives"},
  {s:"Poor", t:"فقير", r:"faqir", c:"Adjectives"},
  {s:"Young", t:"شاب", r:"shabb", c:"Adjectives"},
  {s:"Old", t:"قديم", r:"qadim", c:"Adjectives"},
  {s:"New", t:"جديد", r:"jadid", c:"Adjectives"},
  {s:"Easy", t:"سهل", r:"sahl", c:"Adjectives"},
  {s:"Difficult", t:"صعب", r:"sa'b", c:"Adjectives"},
  {s:"Cheap", t:"رخيص", r:"rakhis", c:"Adjectives"},
  {s:"Expensive", t:"غالي", r:"ghali", c:"Adjectives"},
  {s:"Clean", t:"نظيف", r:"nadif", c:"Adjectives"},
  {s:"Dirty", t:"قذر", r:"qadhir", c:"Adjectives"},
  {s:"Happy", t:"سعيد", r:"sa'id", c:"Adjectives"},
  {s:"Sad", t:"حزين", r:"hazin", c:"Adjectives"},
  {s:"Angry", t:"غاضب", r:"ghadib", c:"Adjectives"},
  {s:"Tired", t:"متعب", r:"mut'ab", c:"Adjectives"},
  {s:"Important", t:"مهم", r:"muhimm", c:"Adjectives"},
  {s:"Strong", t:"قوي", r:"qawi", c:"Adjectives"},
  {s:"Weak", t:"ضعيف", r:"da'if", c:"Adjectives"},
  // Verbs
  {s:"To be", t:"كان", r:"kana", c:"Verbs"},
  {s:"To have", t:"يملك", r:"yamlik", c:"Verbs"},
  {s:"To do", t:"فعل", r:"fa'ala", c:"Verbs"},
  {s:"To go", t:"ذهب", r:"dhahaba", c:"Verbs"},
  {s:"To come", t:"جاء", r:"ja'a", c:"Verbs"},
  {s:"To say", t:"قال", r:"qala", c:"Verbs"},
  {s:"To speak", t:"تكلم", r:"takallama", c:"Verbs"},
  {s:"To ask", t:"سأل", r:"sa'ala", c:"Verbs"},
  {s:"To want", t:"أراد", r:"arada", c:"Verbs"},
  {s:"To need", t:"احتاج", r:"ihtaj", c:"Verbs"},
  {s:"To like", t:"أحب", r:"ahabba", c:"Verbs"},
  {s:"To love", t:"يحب", r:"yuhibb", c:"Verbs"},
  {s:"To know", t:"عرف", r:"arafa", c:"Verbs"},
  {s:"To think", t:"فكر", r:"fakkara", c:"Verbs"},
  {s:"To understand", t:"فهم", r:"fahima", c:"Verbs"},
  {s:"To learn", t:"تعلم", r:"ta'allama", c:"Verbs"},
  {s:"To read", t:"قرأ", r:"qara'a", c:"Verbs"},
  {s:"To write", t:"كتب", r:"kataba", c:"Verbs"},
  {s:"To see", t:"رأى", r:"ra'a", c:"Verbs"},
  {s:"To listen", t:"استمع", r:"istama'a", c:"Verbs"},
  {s:"To walk", t:"مشى", r:"masha", c:"Verbs"},
  {s:"To run", t:"ركض", r:"rakada", c:"Verbs"},
  {s:"To work", t:"عمل", r:"amila", c:"Verbs"},
  {s:"To sleep", t:"نام", r:"nama", c:"Verbs"},
  {s:"To eat", t:"أكل", r:"akala", c:"Verbs"},
  {s:"To drink", t:"شرب", r:"shariba", c:"Verbs"},
  {s:"To buy", t:"اشترى", r:"ishtara", c:"Verbs"},
  {s:"To give", t:"أعطى", r:"a'ta", c:"Verbs"},
  {s:"To open", t:"فتح", r:"fataha", c:"Verbs"},
  {s:"To close", t:"أغلق", r:"aghlaqa", c:"Verbs"},
  {s:"To start", t:"بدأ", r:"bada'a", c:"Verbs"},
  {s:"To finish", t:"أنهى", r:"anha", c:"Verbs"},
  {s:"To help", t:"ساعد", r:"sa'ada", c:"Verbs"},
  {s:"To cry", t:"بكى", r:"baka", c:"Verbs"},
  {s:"To laugh", t:"ضحك", r:"dahika", c:"Verbs"},
  {s:"To forget", t:"نسي", r:"nasiya", c:"Verbs"},
  {s:"To find", t:"وجد", r:"wajada", c:"Verbs"},
  {s:"To wait", t:"انتظر", r:"intazara", c:"Verbs"},
  // Time
  {s:"Time", t:"وقت", r:"waqt", c:"Time"},
  {s:"Day", t:"يوم", r:"yawm", c:"Time"},
  {s:"Week", t:"أسبوع", r:"usbu'", c:"Time"},
  {s:"Month", t:"شهر", r:"shahr", c:"Time"},
  {s:"Year", t:"سنة", r:"sana", c:"Time"},
  {s:"Today", t:"اليوم", r:"al-yawm", c:"Time"},
  {s:"Tomorrow", t:"غداً", r:"ghadan", c:"Time"},
  {s:"Yesterday", t:"أمس", r:"ams", c:"Time"},
  {s:"Morning", t:"صباح", r:"sabah", c:"Time"},
  {s:"Now", t:"الآن", r:"al-an", c:"Time"},
  {s:"Always", t:"دائماً", r:"da'iman", c:"Time"},
  {s:"Never", t:"أبداً", r:"abadan", c:"Time"},
  {s:"Saturday", t:"السبت", r:"as-sabt", c:"Time"},
  {s:"Sunday", t:"الأحد", r:"al-ahad", c:"Time"},
  {s:"Monday", t:"الإثنين", r:"al-ithnayn", c:"Time"},
  {s:"Tuesday", t:"الثلاثاء", r:"ath-thulatha'", c:"Time"},
  {s:"Wednesday", t:"الأربعاء", r:"al-arba'a'", c:"Time"},
  {s:"Thursday", t:"الخميس", r:"al-khamis", c:"Time"},
  {s:"Friday", t:"الجمعة", r:"al-jum'a", c:"Time"},
  // Home
  {s:"House", t:"بيت", r:"bayt", c:"Home"},
  {s:"Door", t:"باب", r:"bab", c:"Home"},
  {s:"Window", t:"نافذة", r:"nafidha", c:"Home"},
  {s:"Bed", t:"سرير", r:"sarir", c:"Home"},
  {s:"Chair", t:"كرسي", r:"kursi", c:"Home"},
  {s:"Table", t:"طاولة", r:"tawila", c:"Home"},
  {s:"Key", t:"مفتاح", r:"miftah", c:"Home"},
  {s:"Kitchen", t:"مطبخ", r:"matbakh", c:"Home"},
  {s:"Garden", t:"حديقة", r:"hadiqa", c:"Home"},
  // Travel
  {s:"Airport", t:"مطار", r:"matar", c:"Travel"},
  {s:"Hotel", t:"فندق", r:"funduq", c:"Travel"},
  {s:"Beach", t:"شاطئ", r:"shati'", c:"Travel"},
  {s:"Mountain", t:"جبل", r:"jabal", c:"Travel"},
  {s:"City", t:"مدينة", r:"madina", c:"Travel"},
  {s:"Country", t:"بلد", r:"balad", c:"Travel"},
  {s:"Street", t:"شارع", r:"shari'", c:"Travel"},
  {s:"Car", t:"سيارة", r:"sayyara", c:"Travel"},
  {s:"Airplane", t:"طائرة", r:"ta'ira", c:"Travel"},
  {s:"Ship", t:"سفينة", r:"safina", c:"Travel"},
  // Weather
  {s:"Weather", t:"طقس", r:"taqs", c:"Weather"},
  {s:"Rain", t:"مطر", r:"matar", c:"Weather"},
  {s:"Sun", t:"شمس", r:"shams", c:"Weather"},
  {s:"Wind", t:"ريح", r:"rih", c:"Weather"},
  {s:"Cloud", t:"سحابة", r:"sahaba", c:"Weather"},
  {s:"Sunny", t:"مشمس", r:"mushmis", c:"Weather"},
  {s:"Rainy", t:"ممطر", r:"mumtir", c:"Weather"},
  {s:"Snow", t:"ثلج", r:"thalj", c:"Weather"},
  // Nature
  {s:"Tree", t:"شجرة", r:"shajara", c:"Nature"},
  {s:"Flower", t:"زهرة", r:"zahra", c:"Nature"},
  {s:"River", t:"نهر", r:"nahr", c:"Nature"},
  {s:"Sea", t:"بحر", r:"bahr", c:"Nature"},
  {s:"Moon", t:"قمر", r:"qamar", c:"Nature"},
  {s:"Star", t:"نجمة", r:"najma", c:"Nature"},
  {s:"Desert", t:"صحراء", r:"sahra'", c:"Nature"},
  {s:"Fire", t:"نار", r:"nar", c:"Nature"},
  // Useful
  {s:"Yes", t:"نعم", r:"na'am", c:"Useful Words"},
  {s:"No", t:"لا", r:"la", c:"Useful Words"},
  {s:"Here", t:"هنا", r:"huna", c:"Useful Words"},
  {s:"There", t:"هناك", r:"hunak", c:"Useful Words"},
  {s:"Where", t:"أين", r:"ayn", c:"Useful Words"},
  {s:"When", t:"متى", r:"mata", c:"Useful Words"},
  {s:"Why", t:"لماذا", r:"limadha", c:"Useful Words"},
  {s:"How", t:"كيف", r:"kayfa", c:"Useful Words"},
  {s:"Who", t:"من", r:"man", c:"Useful Words"},
  {s:"What", t:"ماذا", r:"madha", c:"Useful Words"},
  {s:"This", t:"هذا", r:"hadha", c:"Useful Words"},
  {s:"That", t:"ذلك", r:"dhalik", c:"Useful Words"},
  {s:"And", t:"و", r:"wa", c:"Useful Words"},
  {s:"But", t:"لكن", r:"lakin", c:"Useful Words"},
  {s:"With", t:"مع", r:"ma'a", c:"Useful Words"},
  {s:"From", t:"من", r:"min", c:"Useful Words"},
  {s:"To", t:"إلى", r:"ila", c:"Useful Words"},
  {s:"In", t:"في", r:"fi", c:"Useful Words"},
  {s:"On", t:"على", r:"ala", c:"Useful Words"},
  {s:"Very", t:"جداً", r:"jiddan", c:"Useful Words"},
  {s:"More", t:"أكثر", r:"akthar", c:"Useful Words"},
  {s:"All", t:"كل", r:"kull", c:"Useful Words"},
]

const arSentences = [
  {s:"Hello, how are you?", t:"السلام عليكم، كيف حالك؟", r:"as-salamu alaykum, kayfa haluk"},
  {s:"I am fine, thank you.", t:"أنا بخير، شكراً.", r:"ana bikhayr, shukran"},
  {s:"What is your name?", t:"ما اسمك؟", r:"ma ismuk"},
  {s:"My name is Ahmed.", t:"اسمي أحمد.", r:"ismi ahmad"},
  {s:"Nice to meet you.", t:"تشرفنا.", r:"tasharrafna"},
  {s:"Where are you from?", t:"من أين أنت؟", r:"min ayn anta"},
  {s:"I am from Egypt.", t:"أنا من مصر.", r:"ana min misr"},
  {s:"How old are you?", t:"كم عمرك؟", r:"kam umruk"},
  {s:"I am thirty years old.", t:"عمري ثلاثون سنة.", r:"umri thalathun sana"},
  {s:"Do you speak Arabic?", t:"هل تتكلم العربية؟", r:"hal tatakallam al-arabiya"},
  {s:"I speak a little Arabic.", t:"أتحدث قليلاً من العربية.", r:"atahaddath qalilan min al-arabiya"},
  {s:"What do you do?", t:"ماذا تعمل؟", r:"madha ta'mal"},
  {s:"I am a student.", t:"أنا طالب.", r:"ana talib"},
  {s:"Where do you live?", t:"أين تسكن؟", r:"ayn taskun"},
  {s:"I live in Cairo.", t:"أسكن في القاهرة.", r:"askun fi al-qahira"},
  {s:"Do you have siblings?", t:"هل لديك أخوة؟", r:"hal ladayka ikhwa"},
  {s:"I have two brothers.", t:"لدي أخوان.", r:"ladayya akhawan"},
  {s:"What time is it?", t:"كم الساعة؟", r:"kam al-sa'a"},
  {s:"It is three o'clock.", t:"الساعة الثالثة.", r:"al-sa'a ath-thalitha"},
  {s:"Today is Monday.", t:"اليوم الإثنين.", r:"al-yawm al-ithnayn"},
  {s:"How is the weather?", t:"كيف الطقس؟", r:"kayfa at-taqs"},
  {s:"It is sunny and warm.", t:"الجو مشمس ودافئ.", r:"al-jaww mushmis wa dafi'"},
  {s:"It is raining heavily.", t:"تمطر بغزارة.", r:"tumtir bighazara"},
  {s:"Where is the bathroom?", t:"أين الحمام؟", r:"ayn al-hammam"},
  {s:"The restaurant is on the corner.", t:"المطعم على الزاوية.", r:"al-mat'am ala az-zawiya"},
  {s:"How much does it cost?", t:"كم ثمنه؟", r:"kam thamanuh"},
  {s:"It costs ten dollars.", t:"ثمنه عشرة دولارات.", r:"thamanuh asharat dularat"},
  {s:"I would like a coffee, please.", t:"أريد قهوة من فضلك.", r:"urid qahwa min fadlik"},
  {s:"The food is delicious.", t:"الطعام لذيذ.", r:"at-ta'am ladhidh"},
  {s:"Can I have the bill?", t:"هل يمكنني الحصول على الفاتورة؟", r:"hal yumkinuni al-husul ala al-fatura"},
  {s:"Where is the supermarket?", t:"أين السوبرماركت؟", r:"ayn as-supermarket"},
  {s:"Turn left at the corner.", t:"لف يساراً عند الزاوية.", r:"luf yasaran inda az-zawiya"},
  {s:"Go straight ahead.", t:"اذهب مباشرة.", r:"idhhab mubashara"},
  {s:"The museum is far from here.", t:"المتحف بعيد من هنا.", r:"al-mathaf ba'id min huna"},
  {s:"I am going to the beach tomorrow.", t:"سأذهب إلى الشاطئ غداً.", r:"sa-adhhab ila ash-shati' ghadan"},
  {s:"I love to read books.", t:"أحب قراءة الكتب.", r:"uhibb qira'at al-kutub"},
  {s:"She is very intelligent.", t:"هي ذكية جداً.", r:"hiya dhakiya jiddan"},
  {s:"He is a good friend.", t:"هو صديق جيد.", r:"huwa sadiq jayyid"},
  {s:"I have to work tomorrow.", t:"يجب أن أعمل غداً.", r:"yajib an a'mal ghadan"},
  {s:"She studies at university.", t:"هي تدرس في الجامعة.", r:"hiya tadrus fi al-jami'a"},
  {s:"We are learning Arabic.", t:"نحن نتعلم العربية.", r:"nahnu nata'allam al-arabiya"},
  {s:"Can you help me?", t:"هل يمكنك مساعدتي؟", r:"hal yumkinuka musa'adati"},
  {s:"I don't understand.", t:"لا أفهم.", r:"la afham"},
  {s:"Can you repeat that?", t:"هل يمكنك تكرار ذلك؟", r:"hal yumkinuka takrar dhalik"},
  {s:"Please speak more slowly.", t:"من فضلك تكلم ببطء أكثر.", r:"min fadlik takallam bibu't' akthar"},
  {s:"I am lost.", t:"أنا تائه.", r:"ana ta'ih"},
  {s:"I need a doctor.", t:"أحتاج طبيباً.", r:"ahtaj tabiban"},
  {s:"I have a headache.", t:"عندي صداع.", r:"indi suda'"},
  {s:"I am tired.", t:"أنا متعب.", r:"ana mut'ab"},
  {s:"I am hungry.", t:"أنا جائع.", r:"ana jai'"},
  {s:"I am thirsty.", t:"أنا عطشان.", r:"ana atshan"},
  {s:"What do you want to eat?", t:"ماذا تريد أن تأكل؟", r:"madha turid an ta'kul"},
  {s:"This is very tasty.", t:"هذا لذيذ جداً.", r:"hadha ladhidh jiddan"},
  {s:"Happy birthday!", t:"عيد ميلاد سعيد!", r:"eid milad sa'id"},
  {s:"Congratulations!", t:"مبروك!", r:"mabruk"},
  {s:"I miss you.", t:"أشتاق إليك.", r:"ashtaq ilayk"},
  {s:"I love you.", t:"أحبك.", r:"uhibbuka"},
  {s:"I am sorry.", t:"آسف.", r:"asif"},
  {s:"Don't worry.", t:"لا تقلق.", r:"la taqlaq"},
  {s:"See you later!", t:"أراك لاحقاً!", r:"araka lahiqan"},
  {s:"Take care!", t:"اعتني بنفسك!", r:"i'tani binafsik"},
  {s:"I will call you tonight.", t:"سأتصل بك الليلة.", r:"sa-atasil bika al-layla"},
  {s:"The movie starts at eight.", t:"الفيلم يبدأ في الثامنة.", r:"al-film yabda' fi ath-thamina"},
  {s:"I like this music.", t:"أحب هذه الموسيقى.", r:"uhibb hadhihi al-musiqa"},
  {s:"The hotel is very nice.", t:"الفندق جميل جداً.", r:"al-funduq jamil jiddan"},
  {s:"I lost my passport.", t:"فقدت جواز سفري.", r:"faqadt jawaz safari"},
  {s:"I am here on vacation.", t:"أنا هنا في عطلة.", r:"ana huna fi utla"},
  {s:"Is breakfast included?", t:"هل الفطور مشمول؟", r:"hal al-futur mashmul"},
  {s:"This is too expensive.", t:"هذا غالي جداً.", r:"hadha ghali jiddan"},
  {s:"She is my best friend.", t:"هي صديقتي المفضلة.", r:"hiya sadiqati al-mufaddala"},
  {s:"My mother is a doctor.", t:"أمي طبيبة.", r:"ummi tabiba"},
  {s:"I have two cats.", t:"لدي قطتان.", r:"ladayya qittatan"},
  {s:"I live in a small apartment.", t:"أسكن في شقة صغيرة.", r:"askun fi shiqqa saghira"},
  {s:"I wake up at seven every day.", t:"أستيقظ في السابعة كل يوم.", r:"astayqiz fi as-sabi'a kulla yawm"},
  {s:"I go to work by car.", t:"أذهب إلى العمل بالسيارة.", r:"adhhab ila al-amal bis-sayyara"},
  {s:"I go to bed at eleven.", t:"أنام في الحادية عشرة.", r:"anam fi al-hadiya ashara"},
  {s:"What did you do yesterday?", t:"ماذا فعلت أمس؟", r:"madha fa'alta ams"},
  {s:"I went to the cinema.", t:"ذهبت إلى السينما.", r:"dhahabtu ila as-sinima"},
  {s:"I visited my grandmother.", t:"زرت جدتي.", r:"zurt jaddati"},
  {s:"Tomorrow I will go to the beach.", t:"غداً سأذهب إلى الشاطئ.", r:"ghadan sa-adhhab ila ash-shati'"},
  {s:"I want to travel to Egypt.", t:"أريد السفر إلى مصر.", r:"urid as-safar ila misr"},
  {s:"You look great today!", t:"تبدو رائعاً اليوم!", r:"tabdu ra'i'an al-yawm"},
  {s:"I need to exercise more.", t:"أحتاج إلى ممارسة الرياضة أكثر.", r:"ahtaj ila mumarasat ar-riyada akthar"},
  {s:"The weather is perfect today.", t:"الطقس ممتاز اليوم.", r:"at-taqs mumtaz al-yawm"},
  {s:"Can you open the window?", t:"هل يمكنك فتح النافذة؟", r:"hal yumkinuka fath an-nafidha"},
  {s:"Please close the door.", t:"أغلق الباب من فضلك.", r:"aghliq al-bab min fadlik"},
  {s:"Sit down, please.", t:"اجلس من فضلك.", r:"ijlis min fadlik"},
  {s:"Hurry up!", t:"أسرع!", r:"asri'"},
  {s:"Wait for me!", t:"انتظرني!", r:"intazirni"},
  {s:"Follow me.", t:"اتبعني.", r:"ittabi'ni"},
  {s:"Let's take a walk.", t:"دعنا نتمشى.", r:"da'na natamashsha"},
  {s:"I feel happy today.", t:"أشعر بالسعادة اليوم.", r:"ash'ur bis-sa'ada al-yawm"},
  {s:"Don't be afraid.", t:"لا تخف.", r:"la takhaf"},
  {s:"Everything will be fine.", t:"كل شيء سيكون بخير.", r:"kull shay' sayakun bikhayr"},
  {s:"I believe in you.", t:"أنا أثق بك.", r:"ana athiq bik"},
  {s:"Thank you for everything.", t:"شكراً على كل شيء.", r:"shukran ala kull shay'"},
  {s:"That is a good idea.", t:"تلك فكرة جيدة.", r:"tilka fikra jayyida"},
  {s:"Are you ready?", t:"هل أنت مستعد؟", r:"hal anta musta'id"},
  {s:"Don't forget your keys.", t:"لا تنس مفاتيحك.", r:"la tans mafatihik"},
  {s:"The internet is very slow.", t:"الإنترنت بطيء جداً.", r:"al-internet bati' jiddan"},
  {s:"What are your plans for today?", t:"ما هي خططك لليوم؟", r:"ma hiya khutatuk lil-yawm"},
  {s:"The soup is very hot.", t:"الشوربة ساخنة جداً.", r:"ash-shurba sakhina jiddan"},
  {s:"Please pass me the salt.", t:"ناولني الملح من فضلك.", r:"nawilni al-milh min fadlik"},
  {s:"I drink water every day.", t:"أشرب الماء كل يوم.", r:"ashrab al-ma' kulla yawm"},
  {s:"The baby is crying.", t:"الطفل يبكي.", r:"at-tifl yabki"},
  {s:"I like to spend time with my family.", t:"أحب قضاء الوقت مع عائلتي.", r:"uhibb qada' al-waqt ma'a a'ilati"},
  {s:"Traveling is my passion.", t:"السفر هو شغفي.", r:"as-safar huwa shaghafi"},
  {s:"My dream is to travel around the world.", t:"حلمي هو السفر حول العالم.", r:"hulmi huwa as-safar hawl al-alam"},
  {s:"I need to book a flight.", t:"أحتاج حجز رحلة طيران.", r:"ahtaj hajz rihlat tayaran"},
  {s:"I like my job.", t:"أحب عملي.", r:"uhibb amali"},
  {s:"I am looking for a new job.", t:"أبحث عن عمل جديد.", r:"abhath an amal jadid"},
  {s:"Can you recommend a good restaurant?", t:"هل يمكنك أن توصي بمطعم جيد؟", r:"hal yumkinuka an tusi bi-mat'am jayyid"},
  {s:"The bed is very comfortable.", t:"السرير مريح جداً.", r:"as-sarir murih jiddan"},
  {s:"I had a good night's sleep.", t:"نمنا جيداً الليلة.", r:"nimna jayyidan al-layla"},
  {s:"I took many photos.", t:"أخذت الكثير من الصور.", r:"akhadhtu al-kathir min as-suwar"},
  {s:"I will remember this trip forever.", t:"سأتذكر هذه الرحلة للأبد.", r:"sa-atadhakkar hadhihi ar-rihla lil-abad"},
  {s:"I want to come back again.", t:"أريد العودة مرة أخرى.", r:"urid al-awda marra ukhra"},
  {s:"I feel relaxed and happy.", t:"أشعر بالاسترخاء والسعادة.", r:"ash'ur bil-istirkha' was-sa'ada"},
]

// Assign IDs
let id = 1; for (const w of zhWords) { w.id = id++; }
let sid = 1; for (const s of zhSentences) { s.id = sid++; }

makeWordFile("chinese", "zh", zhWords.map(w => ({id: w.id, s: w.s, t: w.t, r: w.r, c: w.c})), zhSentences.map(s => ({id: s.id, s: s.s, t: s.t, r: s.r})))

id = 1; for (const w of arWords) { w.id = id++; }
sid = 1; for (const s of arSentences) { s.id = sid++; }

makeWordFile("arabic", "ar", arWords.map(w => ({id: w.id, s: w.s, t: w.t, r: w.r, c: w.c})), arSentences.map(s => ({id: s.id, s: s.s, t: s.t, r: s.r})))

console.log("All data files generated!")
