import { writeFileSync } from "fs"
import { join } from "path"

// ─── Spanish data ─────────────────────────────────────────────────────────
const esWords = [
  [25, "Greetings", ["Hello|Hola", "Good morning|Buenos días", "Good afternoon|Buenas tardes",
    "Good evening|Buenas noches", "Goodbye|Adiós", "See you later|Hasta luego",
    "See you tomorrow|Hasta mañana", "Thank you|Gracias", "Thanks a lot|Muchas gracias",
    "You're welcome|De nada", "Please|Por favor", "Excuse me|Disculpe", "Sorry|Lo siento",
    "How are you?|¿Cómo estás?", "I'm fine|Estoy bien", "Nice to meet you|Mucho gusto",
    "Welcome|Bienvenido", "Cheers|Salud", "Bless you|Jesús", "Good luck|Buena suerte",
    "Have a nice day|Que tengas buen día", "Take care|Cuídate", "Long time no see|Cuánto tiempo",
    "What's up?|¿Qué tal?", "Likewise|Igualmente"]],
  [31, "Numbers", ["Zero|Cero", "One|Uno", "Two|Dos", "Three|Tres", "Four|Cuatro", "Five|Cinco",
    "Six|Seis", "Seven|Siete", "Eight|Ocho", "Nine|Nueve", "Ten|Diez", "Eleven|Once",
    "Twelve|Doce", "Thirteen|Trece", "Fourteen|Catorce", "Fifteen|Quince", "Sixteen|Dieciséis",
    "Seventeen|Diecisiete", "Eighteen|Dieciocho", "Nineteen|Diecinueve", "Twenty|Veinte",
    "Thirty|Treinta", "Forty|Cuarenta", "Fifty|Cincuenta", "Sixty|Sesenta", "Seventy|Setenta",
    "Eighty|Ochenta", "Ninety|Noventa", "One hundred|Cien", "One thousand|Mil",
    "One million|Un millón"]],
  [20, "Colors", ["Red|Rojo", "Blue|Azul", "Green|Verde", "Yellow|Amarillo", "Black|Negro",
    "White|Blanco", "Gray|Gris", "Brown|Marrón", "Orange|Naranja", "Pink|Rosa", "Purple|Morado",
    "Gold|Dorado", "Silver|Plateado", "Light|Claro", "Dark|Oscuro", "Bright|Brillante",
    "Colorful|Colorido", "Transparent|Transparente", "Rainbow|Arcoíris", "Beige|Beige"]],
  [90, "Food & Drink", ["Water|Agua", "Coffee|Café", "Tea|Té", "Milk|Leche", "Juice|Jugo",
    "Beer|Cerveza", "Wine|Vino", "Soda|Refresco", "Rice|Arroz", "Bread|Pan", "Chicken|Pollo",
    "Meat|Carne", "Fish|Pescado", "Pork|Cerdo", "Beef|Res", "Egg|Huevo", "Cheese|Queso",
    "Butter|Mantequilla", "Yogurt|Yogur", "Soup|Sopa", "Salad|Ensalada", "Fruit|Fruta",
    "Vegetable|Verdura", "Apple|Manzana", "Banana|Plátano", "Orange|Naranja", "Lemon|Limón",
    "Grape|Uva", "Strawberry|Fresa", "Watermelon|Sandía", "Peach|Melocotón", "Pear|Pera",
    "Cherry|Cereza", "Pineapple|Piña", "Mango|Mango", "Coconut|Coco", "Avocado|Aguacate",
    "Tomato|Tomate", "Potato|Papa", "Onion|Cebolla", "Garlic|Ajo", "Carrot|Zanahoria",
    "Lettuce|Lechuga", "Corn|Maíz", "Bean|Frijol", "Mushroom|Champiñón", "Pepper|Pimiento",
    "Salt|Sal", "Sugar|Azúcar", "Oil|Aceite", "Vinegar|Vinagre", "Honey|Miel",
    "Chocolate|Chocolate", "Cake|Pastel", "Cookie|Galleta", "Ice cream|Helado", "Candy|Caramelo",
    "Breakfast|Desayuno", "Lunch|Almuerzo", "Dinner|Cena", "Snack|Merienda", "Dessert|Postre",
    "Menu|Menú", "Recipe|Receta", "Restaurant|Restaurante", "Waiter|Camarero", "Bill|Cuenta",
    "Glass|Vaso", "Cup|Taza", "Plate|Plato", "Bowl|Cuenco", "Bottle|Botella", "Knife|Cuchillo",
    "Fork|Tenedor", "Spoon|Cuchara", "Napkin|Servilleta", "Table|Mesa", "Chair|Silla",
    "Hungry|Hambriento", "Thirsty|Sediento", "Delicious|Delicioso", "Spicy|Picante",
    "Sweet|Dulce", "Sour|Agrio", "Bitter|Amargo", "Salty|Salado", "Fresh|Fresco",
    "To eat|Comer", "To drink|Beber", "To cook|Cocinar", "To fry|Freír", "To cut|Cortar",
    "To taste|Probar", "To order|Pedir"]],
  [50, "Animals", ["Dog|Perro", "Cat|Gato", "Bird|Pájaro", "Fish|Pez", "Horse|Caballo",
    "Cow|Vaca", "Pig|Cerdo", "Sheep|Oveja", "Goat|Cabra", "Chicken|Gallina", "Duck|Pato",
    "Rabbit|Conejo", "Mouse|Ratón", "Elephant|Elefante", "Lion|León", "Tiger|Tigre",
    "Bear|Oso", "Wolf|Lobo", "Fox|Zorro", "Deer|Ciervo", "Monkey|Mono", "Snake|Serpiente",
    "Turtle|Tortuga", "Frog|Rana", "Eagle|Águila", "Owl|Búho", "Parrot|Loro",
    "Butterfly|Mariposa", "Bee|Abeja", "Ant|Hormiga", "Spider|Araña", "Shark|Tiburón",
    "Whale|Ballena", "Dolphin|Delfín", "Penguin|Pingüino", "Swan|Cisne", "Hawk|Halcón",
    "Squirrel|Ardilla", "Hedgehog|Erizo", "Bat|Murciélago", "Crab|Cangrejo", "Lobster|Langosta",
    "Snail|Caracol", "Mosquito|Mosquito", "Fly|Mosca", "Cockroach|Cucaracha", "Worm|Gusano",
    "Lizard|Lagarto", "Seal|Foca", "Octopus|Pulpo"]],
  [35, "Body", ["Head|Cabeza", "Hair|Cabello", "Face|Cara", "Eye|Ojo", "Ear|Oreja",
    "Nose|Nariz", "Mouth|Boca", "Tooth|Diente", "Tongue|Lengua", "Lip|Labio", "Neck|Cuello",
    "Shoulder|Hombro", "Arm|Brazo", "Elbow|Codo", "Hand|Mano", "Finger|Dedo", "Thumb|Pulgar",
    "Nail|Uña", "Chest|Pecho", "Back|Espalda", "Stomach|Estómago", "Leg|Pierna", "Knee|Rodilla",
    "Foot|Pie", "Ankle|Tobillo", "Heel|Talón", "Toe|Dedo del pie", "Skin|Piel", "Bone|Hueso",
    "Blood|Sangre", "Heart|Corazón", "Brain|Cerebro", "Muscle|Músculo", "Throat|Garganta",
    "Wrist|Muñeca"]],
  [30, "Clothing", ["Shirt|Camisa", "Pants|Pantalones", "Jacket|Chaqueta", "Coat|Abrigo",
    "Sweater|Suéter", "Dress|Vestido", "Skirt|Falda", "Suit|Traje", "Tie|Corbata",
    "Shoes|Zapatos", "Boots|Botas", "Socks|Calcetines", "Hat|Sombrero", "Gloves|Guantes",
    "Scarf|Bufanda", "Belt|Cinturón", "Watch|Reloj", "Ring|Anillo", "Earrings|Aretes",
    "Necklace|Collar", "Bracelet|Pulsera", "Wallet|Cartera", "Backpack|Mochila",
    "Umbrella|Paraguas", "Sunglasses|Gafas de sol", "Pajamas|Pijama", "Swimsuit|Traje de baño",
    "Uniform|Uniforme", "Pocket|Bolsillo", "Button|Botón"]],
  [40, "People", ["Mother|Madre", "Father|Padre", "Sister|Hermana", "Brother|Hermano",
    "Daughter|Hija", "Son|Hijo", "Wife|Esposa", "Husband|Esposo", "Grandmother|Abuela",
    "Grandfather|Abuelo", "Aunt|Tía", "Uncle|Tío", "Cousin|Primo", "Niece|Sobrina",
    "Nephew|Sobrino", "Friend|Amigo", "Neighbor|Vecino", "Colleague|Compañero", "Boss|Jefe",
    "Teacher|Profesor", "Student|Estudiante", "Doctor|Médico", "Nurse|Enfermero", "Baby|Bebé",
    "Child|Niño", "Adult|Adulto", "Man|Hombre", "Woman|Mujer", "Boy|Muchacho", "Girl|Muchacha",
    "Person|Persona", "Name|Nombre", "Age|Edad", "Family|Familia", "Couple|Pareja",
    "Guest|Invitado", "Host|Anfitrión", "Stranger|Extraño", "Partner|Compañero", "Owner|Dueño"]],
  [100, "Adjectives", ["Big|Grande", "Small|Pequeño", "Tall|Alto", "Short|Bajo", "Long|Largo",
    "Short len|Corto", "Wide|Ancho", "Narrow|Estrecho", "Thick|Grueso", "Thin|Delgado",
    "Heavy|Pesado", "Light|Ligero", "Fast|Rápido", "Slow|Lento", "Hot|Caliente", "Cold|Frío",
    "Warm|Tibio", "Cool|Fresco", "Good|Bueno", "Bad|Malo", "Beautiful|Hermoso", "Ugly|Feo",
    "Rich|Rico", "Poor|Pobre", "Young|Joven", "Old|Viejo", "New|Nuevo", "Old thing|Antiguo",
    "Easy|Fácil", "Difficult|Difícil", "Cheap|Barato", "Expensive|Caro", "Clean|Limpio",
    "Dirty|Sucio", "Full|Lleno", "Empty|Vacío", "Open|Abierto", "Closed|Cerrado", "Hard|Duro",
    "Soft|Suave", "Strong|Fuerte", "Weak|Débil", "Happy|Feliz", "Sad|Triste", "Angry|Enojado",
    "Calm|Tranquilo", "Nervous|Nervioso", "Brave|Valiente", "Shy|Tímido", "Smart|Inteligente",
    "Funny|Gracioso", "Serious|Serio", "Polite|Educado", "Rude|Grosero", "Kind|Amable",
    "Mean|Malvado", "Generous|Generoso", "Selfish|Egoísta", "Honest|Honesto", "Lazy|Perezoso",
    "Hardworking|Trabajador", "Tired|Cansado", "Sick|Enfermo", "Healthy|Saludable",
    "Important|Importante", "Necessary|Necesario", "Possible|Posible", "Impossible|Imposible",
    "Ready|Listo", "Sure|Seguro", "Wrong|Incorrecto", "Correct|Correcto", "Free|Libre",
    "Busy|Ocupado", "Same|Mismo", "Different|Diferente", "Real|Real", "False|Falso",
    "Deep|Profundo", "Shallow|Superficial", "Smooth|Suave", "Rough|Áspero", "Sharp|Filoso",
    "Dull|Opaco", "Wet|Mojado", "Dry|Seco", "Safe|Seguro", "Dangerous|Peligroso",
    "Comfortable|Cómodo", "Uncomfortable|Incómodo", "Wonderful|Maravilloso", "Terrible|Terrible",
    "Excellent|Excelente", "Curious|Curioso", "Modern|Moderno", "Traditional|Tradicional",
    "Popular|Popular", "Famous|Famoso", "Strange|Extraño", "Normal|Normal", "Natural|Natural",
    "Artificial|Artificial"]],
  [130, "Verbs", ["To be|Ser", "To have|Tener", "To do|Hacer", "To go|Ir", "To come|Venir",
    "To say|Decir", "To speak|Hablar", "To tell|Contar", "To ask|Preguntar", "To answer|Responder",
    "To want|Querer", "To need|Necesitar", "To like|Gustar", "To love|Amar", "To hate|Odiar",
    "To know|Saber", "To know p|Conocer", "To think|Pensar", "To believe|Creer",
    "To understand|Entender", "To learn|Aprender", "To teach|Enseñar", "To study|Estudiar",
    "To read|Leer", "To write|Escribir", "To see|Ver", "To watch|Mirar", "To hear|Oír",
    "To listen|Escuchar", "To walk|Caminar", "To run|Correr", "To swim|Nadar", "To fly|Volar",
    "To drive|Conducir", "To travel|Viajar", "To arrive|Llegar", "To leave|Salir",
    "To stay|Quedarse", "To enter|Entrar", "To return|Volver", "To buy|Comprar", "To sell|Vender",
    "To pay|Pagar", "To cost|Costar", "To give|Dar", "To take|Tomar", "To bring|Traer",
    "To carry|Llevar", "To put|Poner", "To find|Encontrar", "To lose|Perder", "To look for|Buscar",
    "To wait|Esperar", "To open|Abrir", "To close|Cerrar", "To start|Empezar", "To finish|Terminar",
    "To continue|Continuar", "To change|Cambiar", "To work|Trabajar", "To rest|Descansar",
    "To sleep|Dormir", "To wake|Despertarse", "To get up|Levantarse", "To wash|Lavar",
    "To clean|Limpiar", "To dress|Vestirse", "To sit|Sentarse", "To stand|Pararse",
    "To lie down|Acostarse", "To laugh|Reír", "To cry|Llorar", "To smile|Sonreír",
    "To sing|Cantar", "To dance|Bailar", "To play|Jugar", "To win|Ganar", "To try|Intentar",
    "To help|Ayudar", "To call|Llamar", "To send|Enviar", "To receive|Recibir", "To show|Mostrar",
    "To explain|Explicar", "To remember|Recordar", "To forget|Olvidar", "To choose|Elegir",
    "To decide|Decidir", "To allow|Permitir", "To forbid|Prohibir", "To promise|Prometer",
    "To refuse|Rechazar", "To accept|Aceptar", "To invite|Invitar", "To visit|Visitar",
    "To meet|Conocer", "To introduce|Presentar", "To apologize|Disculparse", "To thank|Agradecer",
    "To celebrate|Celebrar", "To suffer|Sufrir", "To feel|Sentir", "To hope|Esperar",
    "To wish|Desear", "To deserve|Merecer", "To trust|Confiar", "To doubt|Dudar",
    "To warn|Advertir", "To insist|Insistir", "To suggest|Sugerir", "To recommend|Recomendar",
    "To complain|Quejarse", "To argue|Discutir", "To agree|Acordar", "To disagree|Discrepar",
    "To offer|Ofrecer", "To borrow|Pedir prestado", "To lend|Prestar", "To rent|Alquilar",
    "To share|Compartir", "To repeat|Repetir", "To practice|Practicar", "To improve|Mejorar",
    "To prepare|Preparar", "To organize|Organizar", "To plan|Planear", "To build|Construir",
    "To grow|Crecer", "To fix|Arreglar", "To break|Romper", "To fall|Caer", "To lift|Levantar",
    "To push|Empujar", "To pull|Jalar", "To throw|Lanzar", "To catch|Atrapar", "To hide|Esconder",
    "To follow|Seguir", "To fight|Luchar"]],
  [45, "Time", ["Time|Tiempo", "Hour|Hora", "Minute|Minuto", "Second|Segundo", "Day|Día",
    "Night|Noche", "Week|Semana", "Month|Mes", "Year|Año", "Today|Hoy", "Tomorrow|Mañana",
    "Yesterday|Ayer", "Morning|Mañana", "Afternoon|Tarde", "Evening|Noche", "Now|Ahora",
    "Later|Después", "Early|Temprano", "Late|Tarde", "Always|Siempre", "Never|Nunca",
    "Sometimes|A veces", "Often|A menudo", "Rarely|Rara vez", "Already|Ya", "Not yet|Todavía no",
    "Soon|Pronto", "Immediately|Inmediatamente", "Before|Antes", "After|Después", "During|Durante",
    "Until|Hasta", "Since|Desde", "Monday|Lunes", "Tuesday|Martes", "Wednesday|Miércoles",
    "Thursday|Jueves", "Friday|Viernes", "Saturday|Sábado", "Sunday|Domingo", "January|Enero",
    "February|Febrero", "March|Marzo", "April|Abril", "May|Mayo", "June|Junio", "July|Julio",
    "August|Agosto", "September|Septiembre", "October|Octubre", "November|Noviembre",
    "December|Diciembre"]],
  [45, "Home", ["House|Casa", "Apartment|Apartamento", "Room|Cuarto", "Door|Puerta",
    "Window|Ventana", "Wall|Pared", "Floor|Piso", "Ceiling|Techo", "Bed|Cama", "Table|Mesa",
    "Chair|Silla", "Sofa|Sofá", "Lamp|Lámpara", "Clock|Reloj", "Mirror|Espejo", "Towel|Toalla",
    "Soap|Jabón", "Shampoo|Champú", "Toothbrush|Cepillo de dientes", "Toilet|Inodoro",
    "Shower|Ducha", "Bathtub|Bañera", "Stove|Estufa", "Oven|Horno", "Microwave|Microondas",
    "Refrigerator|Refrigerador", "Sink|Fregadero", "Trash|Basura", "Key|Llave", "Lock|Cerradura",
    "Stairs|Escaleras", "Garden|Jardín", "Balcony|Balcón", "Garage|Garaje", "Roof|Techo",
    "Basement|Sótano", "Furniture|Muebles", "Carpet|Alfombra", "Pillow|Almohada",
    "Blanket|Manta", "Curtain|Cortina", "Drawer|Cajón", "Shelf|Estante", "Wardrobe|Armario",
    "Washing machine|Lavadora"]],
  [40, "Travel", ["Airport|Aeropuerto", "Train station|Estación de tren", "Bus stop|Parada de autobús",
    "Ticket|Boleto", "Passport|Pasaporte", "Luggage|Equipaje", "Map|Mapa", "Hotel|Hotel",
    "Reservation|Reservación", "Beach|Playa", "Mountain|Montaña", "City|Ciudad", "Country|País",
    "Trip|Viaje", "Tour|Tour", "Guide|Guía", "Souvenir|Recuerdo", "Camera|Cámara",
    "Suitcase|Maleta", "Boarding pass|Tarjeta de embarque", "Customs|Aduana", "Visa|Visa",
    "Airplane|Avión", "Train|Tren", "Bus|Autobús", "Taxi|Taxi", "Subway|Metro", "Ship|Barco",
    "Bicycle|Bicicleta", "Motorcycle|Motocicleta", "Highway|Autopista", "Street|Calle",
    "Corner|Esquina", "Bridge|Puente", "Parking|Estacionamiento", "One way|Sencillo",
    "Round trip|Ida y vuelta", "Departure|Salida", "Arrival|Llegada", "Delay|Retraso"]],
  [30, "Weather", ["Weather|Clima", "Rain|Lluvia", "Snow|Nieve", "Wind|Viento", "Sun|Sol",
    "Cloud|Nube", "Storm|Tormenta", "Thunder|Trueno", "Lightning|Rayo", "Fog|Niebla",
    "Ice|Hielo", "Heat|Calor", "Hurricane|Huracán", "Flood|Inundación", "Drought|Sequía",
    "Humidity|Humedad", "Temperature|Temperatura", "Degree|Grado", "Forecast|Pronóstico",
    "Sunny|Soleado", "Cloudy|Nublado", "Rainy|Lluvioso", "Snowy|Nevado", "Windy|Ventoso",
    "Foggy|Neblinoso", "Clear|Despejado", "Stormy|Tormentoso", "Mild|Templado",
    "Freezing|Helado", "Climate|Clima"]],
  [35, "Nature", ["Tree|Árbol", "Flower|Flor", "Grass|Hierba", "Forest|Bosque", "River|Río",
    "Lake|Lago", "Ocean|Océano", "Sea|Mar", "Sky|Cielo", "Star|Estrella", "Moon|Luna",
    "Earth|Tierra", "Fire|Fuego", "Air|Aire", "Soil|Suelo", "Rock|Roca", "Sand|Arena",
    "Island|Isla", "Hill|Colina", "Valley|Valle", "Desert|Desierto", "Jungle|Selva",
    "Volcano|Volcán", "Waterfall|Cascada", "Field|Campo", "Path|Sendero", "Sunrise|Amanecer",
    "Sunset|Atardecer", "Shadow|Sombra", "Cave|Cueva", "Wave|Ola", "Mountain range|Cordillera",
    "Planet|Planeta", "Forest|Bosque", "Nature|Naturaleza"]],
  [35, "Occupations", ["Doctor|Médico", "Nurse|Enfermero", "Teacher|Maestro", "Engineer|Ingeniero",
    "Lawyer|Abogado", "Accountant|Contador", "Architect|Arquitecto", "Journalist|Periodista",
    "Pilot|Piloto", "Police|Policía", "Firefighter|Bombero", "Farmer|Granjero", "Chef|Cocinero",
    "Artist|Artista", "Musician|Músico", "Writer|Escritor", "Singer|Cantante", "Athlete|Atleta",
    "Scientist|Científico", "Programmer|Programador", "Dentist|Dentista", "Veterinarian|Veterinario",
    "Psychologist|Psicólogo", "Pharmacist|Farmacéutico", "Electrician|Electricista",
    "Plumber|Plomero", "Mechanic|Mecánico", "Carpenter|Carpintero", "Driver|Conductor",
    "Secretary|Secretario", "Manager|Gerente", "Director|Director", "CEO|Director ejecutivo",
    "Soldier|Soldado", "Judge|Juez"]],
  [25, "Emotions", ["Love|Amor", "Hate|Odio", "Joy|Alegría", "Sadness|Tristeza", "Fear|Miedo",
    "Anger|Ira", "Surprise|Sorpresa", "Disgust|Asco", "Trust|Confianza", "Hope|Esperanza",
    "Pride|Orgullo", "Shame|Vergüenza", "Envy|Envidia", "Gratitude|Gratitud", "Compassion|Compasión",
    "Loneliness|Soledad", "Excitement|Emoción", "Boredom|Aburrimiento", "Worry|Preocupación",
    "Confusion|Confusión", "Curiosity|Curiosidad", "Peace|Paz", "Stress|Estrés", "Courage|Coraje",
    "Patience|Paciencia"]],
  [30, "Technology", ["Computer|Computadora", "Laptop|Portátil", "Phone|Teléfono",
    "Smartphone|Celular", "Tablet|Tableta", "Internet|Internet", "Website|Sitio web",
    "Email|Correo electrónico", "Password|Contraseña", "Username|Nombre de usuario",
    "Screen|Pantalla", "Keyboard|Teclado", "Mouse|Ratón", "Printer|Impresora", "Speaker|Altavoz",
    "Headphones|Auriculares", "Camera|Cámara", "Battery|Batería", "Charger|Cargador",
    "App|Aplicación", "Software|Software", "Hardware|Hardware", "File|Archivo", "Folder|Carpeta",
    "Download|Descargar", "Upload|Subir", "Search|Buscar", "Click|Clic", "Text message|Mensaje",
    "Social media|Redes sociales"]],
  [50, "Useful Words", ["In|En", "On|Sobre", "Under|Debajo", "With|Con", "Without|Sin", "For|Para",
    "By|Por", "From|De", "To|A", "About|Sobre", "Between|Entre", "Through|A través",
    "Above|Encima", "Below|Abajo", "Behind|Detrás", "In front|Delante", "Next to|Al lado",
    "Inside|Dentro", "Outside|Fuera", "Here|Aquí", "There|Allí", "Where|Dónde", "When|Cuándo",
    "Why|Por qué", "How|Cómo", "Who|Quién", "What|Qué", "Which|Cuál", "This|Este", "That|Ese",
    "These|Estos", "Those|Esos", "Some|Algunos", "All|Todo", "Many|Mucho", "Few|Poco",
    "More|Más", "Less|Menos", "Very|Muy", "Too|Demasiado", "Only|Solo", "Also|También",
    "But|Pero", "And|Y", "Or|O", "Because|Porque", "If|Si", "Although|Aunque", "Then|Entonces",
    "While|Mientras"]],
]

const esSentences = [
  "Hello, how are you?|Hola, ¿cómo estás?",
  "I am fine, thank you.|Estoy bien, gracias.",
  "What is your name?|¿Cómo te llamas?",
  "My name is Maria.|Me llamo María.",
  "Nice to meet you.|Mucho gusto.",
  "Where are you from?|¿De dónde eres?",
  "I am from Spain.|Soy de España.",
  "How old are you?|¿Cuántos años tienes?",
  "I am twenty years old.|Tengo veinte años.",
  "Do you speak Spanish?|¿Hablas español?",
  "I speak a little Spanish.|Hablo un poco de español.",
  "What do you do?|¿A qué te dedicas?",
  "I am a student.|Soy estudiante.",
  "I work as a teacher.|Trabajo como maestro.",
  "Where do you live?|¿Dónde vives?",
  "I live in Mexico City.|Vivo en la Ciudad de México.",
  "Do you have siblings?|¿Tienes hermanos?",
  "I have one brother and one sister.|Tengo un hermano y una hermana.",
  "What time is it?|¿Qué hora es?",
  "It is two o'clock.|Son las dos.",
  "What day is today?|¿Qué día es hoy?",
  "Today is Monday.|Hoy es lunes.",
  "What is the date?|¿Cuál es la fecha?",
  "Today is the first of January.|Hoy es primero de enero.",
  "How is the weather?|¿Cómo está el clima?",
  "It is sunny and warm.|Está soleado y cálido.",
  "It is raining heavily.|Está lloviendo mucho.",
  "I like your shirt.|Me gusta tu camisa.",
  "Where is the bathroom?|¿Dónde está el baño?",
  "The restaurant is on the corner.|El restaurante está en la esquina.",
  "How much does it cost?|¿Cuánto cuesta?",
  "It costs ten dollars.|Cuesta diez dólares.",
  "I would like a coffee, please.|Quisiera un café, por favor.",
  "The food is delicious.|La comida está deliciosa.",
  "Can I have the bill?|¿Me puede traer la cuenta?",
  "I need to buy groceries.|Necesito comprar víveres.",
  "Where is the supermarket?|¿Dónde está el supermercado?",
  "Turn left at the corner.|Gira a la izquierda en la esquina.",
  "Go straight ahead.|Sigue derecho.",
  "The museum is far from here.|El museo está lejos de aquí.",
  "I am going to the beach tomorrow.|Voy a la playa mañana.",
  "We went to the mountains last weekend.|Fuimos a las montañas el fin de semana pasado.",
  "I love to read books.|Me encanta leer libros.",
  "She is very intelligent.|Ella es muy inteligente.",
  "He is a good friend.|Él es un buen amigo.",
  "We are happy to see you.|Estamos felices de verte.",
  "They arrived late to the party.|Llegaron tarde a la fiesta.",
  "I have to work tomorrow.|Tengo que trabajar mañana.",
  "She studies at the university.|Ella estudia en la universidad.",
  "He runs every morning.|Él corre todas las mañanas.",
  "I like to swim in the ocean.|Me gusta nadar en el océano.",
  "We are learning Spanish.|Estamos aprendiendo español.",
  "Can you help me?|¿Puedes ayudarme?",
  "Of course, with pleasure.|Claro, con gusto.",
  "I don't understand.|No entiendo.",
  "Can you repeat, please?|¿Puedes repetir, por favor?",
  "Please speak more slowly.|Por favor habla más despacio.",
  "I am lost.|Estoy perdido.",
  "Call the police!|¡Llama a la policía!",
  "I need a doctor.|Necesito un médico.",
  "Where is the hospital?|¿Dónde está el hospital?",
  "I have a headache.|Me duele la cabeza.",
  "I am tired.|Estoy cansado.",
  "I am hungry.|Tengo hambre.",
  "I am thirsty.|Tengo sed.",
  "Let's eat together.|Comamos juntos.",
  "What do you want to eat?|¿Qué quieres comer?",
  "I want pizza for dinner.|Quiero pizza para la cena.",
  "This is very tasty.|Esto está muy sabroso.",
  "I don't like spicy food.|No me gusta la comida picante.",
  "Do you have any allergies?|¿Tienes alguna alergia?",
  "I am vegetarian.|Soy vegetariano.",
  "Cheers to your health!|¡Salud por tu salud!",
  "Happy birthday!|¡Feliz cumpleaños!",
  "Merry Christmas!|¡Feliz Navidad!",
  "Happy New Year!|¡Feliz Año Nuevo!",
  "Congratulations!|¡Felicidades!",
  "I miss you.|Te extraño.",
  "I love you.|Te quiero.",
  "You are beautiful.|Eres hermosa.",
  "I am sorry.|Lo siento.",
  "Don't worry.|No te preocupes.",
  "It doesn't matter.|No importa.",
  "Have a good trip!|¡Buen viaje!",
  "See you later!|¡Hasta luego!",
  "See you tomorrow!|¡Hasta mañana!",
  "Take care!|¡Cuídate!",
  "Write me an email.|Escríbeme un correo.",
  "I will call you tonight.|Te llamaré esta noche.",
  "Let's meet at the cafe.|Encontrémonos en el café.",
  "I am waiting for you.|Te estoy esperando.",
  "The movie starts at eight.|La película empieza a las ocho.",
  "Do you want to dance?|¿Quieres bailar?",
  "I like this music.|Me gusta esta música.",
  "Can you take a photo of us?|¿Puedes tomarnos una foto?",
  "What a beautiful view!|¡Qué vista tan hermosa!",
  "I need to charge my phone.|Necesito cargar mi teléfono.",
  "What is the WiFi password?|¿Cuál es la contraseña del WiFi?",
  "I have a reservation.|Tengo una reservación.",
  "I want to rent a car.|Quiero alquilar un coche.",
  "The flight was delayed.|El vuelo se retrasó.",
  "I lost my passport.|Perdí mi pasaporte.",
  "Can you help me find my luggage?|¿Puedes ayudarme a encontrar mi equipaje?",
  "I am here on vacation.|Estoy aquí de vacaciones.",
  "I am traveling for business.|Viajo por negocios.",
  "The hotel is very nice.|El hotel es muy bonito.",
  "I need a room for two nights.|Necesito una habitación por dos noches.",
  "What time is check-out?|¿A qué hora es la salida?",
  "Is breakfast included?|¿El desayuno está incluido?",
  "I would like a window seat.|Quisiera un asiento de ventana.",
  "The food on the plane was good.|La comida del avión estaba buena.",
  "I bought souvenirs for my family.|Compré recuerdos para mi familia.",
  "The museum opens at ten.|El museo abre a las diez.",
  "I need to exchange money.|Necesito cambiar dinero.",
  "What is the exchange rate?|¿Cuál es el tipo de cambio?",
  "I don't have cash.|No tengo efectivo.",
  "Can I pay with card?|¿Puedo pagar con tarjeta?",
  "Is there a discount?|¿Hay algún descuento?",
  "This is too expensive.|Esto es demasiado caro.",
  "Do you have something cheaper?|¿Tienes algo más barato?",
  "I'll take it.|Lo llevo.",
  "I am just looking.|Solo estoy mirando.",
  "Can I try this on?|¿Puedo probarme esto?",
  "What size is this?|¿Qué talla es esta?",
  "I need a smaller size.|Necesito una talla más pequeña.",
  "Do you have this in blue?|¿Tienes esto en azul?",
  "I like this color.|Me gusta este color.",
  "The shoes are very comfortable.|Los zapatos son muy cómodos.",
  "I need to buy a gift.|Necesito comprar un regalo.",
  "She is my best friend.|Ella es mi mejor amiga.",
  "He is my brother.|Él es mi hermano.",
  "My mother is a doctor.|Mi madre es médica.",
  "My father is an engineer.|Mi padre es ingeniero.",
  "I have two cats and a dog.|Tengo dos gatos y un perro.",
  "My house has three bedrooms.|Mi casa tiene tres habitaciones.",
  "I live in a small apartment.|Vivo en un apartamento pequeño.",
  "The kitchen is very modern.|La cocina es muy moderna.",
  "I need to clean the bathroom.|Necesito limpiar el baño.",
  "The garden is beautiful.|El jardín es hermoso.",
  "I wake up at seven every day.|Me despierto a las siete todos los días.",
  "I take a shower in the morning.|Me ducho por la mañana.",
  "I have breakfast at eight.|Desayuno a las ocho.",
  "I go to work by bus.|Voy al trabajo en autobús.",
  "I finish work at five.|Termino el trabajo a las cinco.",
  "I go to bed at eleven.|Me acuesto a las once.",
  "What did you do yesterday?|¿Qué hiciste ayer?",
  "I went to the cinema.|Fui al cine.",
  "I watched a good movie.|Vi una buena película.",
  "I read an interesting book.|Leí un libro interesante.",
  "I visited my grandmother.|Visité a mi abuela.",
  "I cooked dinner for my family.|Cociné la cena para mi familia.",
  "I studied for the exam.|Estudié para el examen.",
  "I went shopping with my friends.|Fui de compras con mis amigos.",
  "I listened to music all day.|Escuché música todo el día.",
  "I played soccer in the park.|Jugué fútbol en el parque.",
  "Tomorrow I will go to the beach.|Mañana iré a la playa.",
  "Next week I have a vacation.|La próxima semana tengo vacaciones.",
  "I want to travel to Japan.|Quiero viajar a Japón.",
  "I need to buy a new car.|Necesito comprar un coche nuevo.",
  "I am learning to play guitar.|Estoy aprendiendo a tocar la guitarra.",
  "I like to cook Italian food.|Me gusta cocinar comida italiana.",
  "We should go out for dinner.|Deberíamos salir a cenar.",
  "I feel very tired today.|Me siento muy cansado hoy.",
  "You look great today!|¡Te ves genial hoy!",
  "I need to exercise more.|Necesito hacer más ejercicio.",
  "The park is very quiet.|El parque está muy tranquilo.",
  "Barcelona is a beautiful city.|Barcelona es una ciudad hermosa.",
  "I have never been to South America.|Nunca he estado en Sudamérica.",
  "I would like to visit Argentina.|Me gustaría visitar Argentina.",
  "The people here are very friendly.|La gente aquí es muy amable.",
  "I love the food in this country.|Me encanta la comida de este país.",
  "The weather is perfect today.|El clima está perfecto hoy.",
  "It is very cold in winter.|Hace mucho frío en invierno.",
  "Summer is my favorite season.|El verano es mi estación favorita.",
  "I like spring because of the flowers.|Me gusta la primavera por las flores.",
  "Autumn leaves are beautiful.|Las hojas de otoño son hermosas.",
  "Can you open the window, please?|¿Puedes abrir la ventana, por favor?",
  "Please close the door.|Por favor, cierra la puerta.",
  "Turn off the lights.|Apaga las luces.",
  "Turn on the television.|Enciende la televisión.",
  "Sit down, please.|Siéntate, por favor.",
  "Stand up, please.|Levántate, por favor.",
  "Be quiet, please.|Silencio, por favor.",
  "Hurry up!|¡Date prisa!",
  "Wait for me!|¡Espérame!",
  "Follow me.|Sígueme.",
  "I will show you the way.|Te mostraré el camino.",
  "Let's take a walk.|Vamos a dar un paseo.",
  "The children are playing outside.|Los niños están jugando afuera.",
  "The dog is sleeping on the sofa.|El perro está durmiendo en el sofá.",
  "I need to feed the cat.|Necesito darle de comer al gato.",
  "The flowers in the garden are blooming.|Las flores del jardín están floreciendo.",
  "I like rainy days.|Me gustan los días lluviosos.",
  "The stars are very bright tonight.|Las estrellas están muy brillantes esta noche.",
  "I enjoy watching the sunset.|Disfruto ver el atardecer.",
  "Do you want to go for a walk?|¿Quieres dar un paseo?",
  "I feel happy today.|Me siento feliz hoy.",
  "Why are you sad?|¿Por qué estás triste?",
  "I am nervous about the exam.|Estoy nervioso por el examen.",
  "Don't be afraid.|No tengas miedo.",
  "Everything will be fine.|Todo va a estar bien.",
  "I believe in you.|Creo en ti.",
  "You can do it!|¡Tú puedes hacerlo!",
  "I am proud of you.|Estoy orgulloso de ti.",
  "Thank you for everything.|Gracias por todo.",
  "You are welcome.|De nada.",
  "I appreciate your help.|Agradezco tu ayuda.",
  "It was my pleasure.|Fue un placer.",
  "I agree with you.|Estoy de acuerdo contigo.",
  "I don't think so.|No lo creo.",
  "Maybe you are right.|Quizás tienes razón.",
  "I am not sure.|No estoy seguro.",
  "Let me think about it.|Déjame pensar.",
  "That is a good idea.|Esa es una buena idea.",
  "I prefer the red one.|Prefiero el rojo.",
  "This is better than that.|Esto es mejor que eso.",
  "Which one do you want?|¿Cuál quieres?",
  "I don't have any preference.|No tengo preferencia.",
  "It's up to you.|Depende de ti.",
  "I will be there soon.|Estaré allí pronto.",
  "Are you ready?|¿Estás listo?",
  "I am not ready yet.|No estoy listo todavía.",
  "I need five more minutes.|Necesito cinco minutos más.",
  "What time should we meet?|¿A qué hora nos encontramos?",
  "Let's meet at six.|Encontrémonos a las seis.",
  "I'll pick you up at seven.|Te recojo a las siete.",
  "Don't forget your keys.|No olvides tus llaves.",
  "I left my phone at home.|Dejé mi teléfono en casa.",
  "Can I borrow your charger?|¿Me prestas tu cargador?",
  "My computer is not working.|Mi computadora no funciona.",
  "The internet is very slow.|El internet está muy lento.",
  "I will send you the document.|Te enviaré el documento.",
  "Did you receive my message?|¿Recibiste mi mensaje?",
  "I will check my email.|Revisaré mi correo.",
  "Please reply as soon as possible.|Por favor responde lo antes posible.",
  "I look forward to hearing from you.|Espero saber de ti pronto.",
  "Have a nice weekend!|¡Que tengas buen fin de semana!",
  "What are your plans for today?|¿Cuáles son tus planes para hoy?",
  "I have nothing planned.|No tengo planes.",
  "Let's do something fun.|Hagamos algo divertido.",
  "I want to learn to cook.|Quiero aprender a cocinar.",
  "The soup is very hot.|La sopa está muy caliente.",
  "Be careful, it's hot.|Ten cuidado, está caliente.",
  "I burned my tongue.|Me quemé la lengua.",
  "This knife is very sharp.|Este cuchillo está muy filoso.",
  "Can you cut the vegetables?|¿Puedes cortar las verduras?",
  "The table is set for dinner.|La mesa está puesta para la cena.",
  "Please pass me the salt.|Por favor pásame la sal.",
  "This dish needs more salt.|Este plato necesita más sal.",
  "I am on a diet.|Estoy a dieta.",
  "I want to lose weight.|Quiero perder peso.",
  "You should eat more vegetables.|Deberías comer más verduras.",
  "Fruit is good for your health.|La fruta es buena para la salud.",
  "I drink two liters of water daily.|Bebo dos litros de agua al día.",
  "I don't drink alcohol.|No bebo alcohol.",
  "This coffee is delicious.|Este café está delicioso.",
  "I need a glass of water.|Necesito un vaso de agua.",
  "The baby is crying.|El bebé está llorando.",
  "The children are laughing.|Los niños están riendo.",
  "My grandmother tells great stories.|Mi abuela cuenta historias increíbles.",
  "I like to spend time with my family.|Me gusta pasar tiempo con mi familia.",
  "We have dinner together every Sunday.|Cenamos juntos todos los domingos.",
  "I miss my home country.|Extraño mi país de origen.",
  "I want to learn about other cultures.|Quiero aprender sobre otras culturas.",
  "Traveling is my passion.|Viajar es mi pasión.",
  "I have visited many countries.|He visitado muchos países.",
  "I prefer mountains over beaches.|Prefiero las montañas a las playas.",
  "The view from the top is amazing.|La vista desde la cima es increíble.",
  "I climbed a volcano last year.|Subí un volcán el año pasado.",
  "The desert is very hot during the day.|El desierto está muy caliente durante el día.",
  "I saw a whale in the ocean.|Vi una ballena en el océano.",
  "I want to learn to dive.|Quiero aprender a bucear.",
  "We need to protect the environment.|Necesitamos proteger el medio ambiente.",
  "Recycling is very important.|Reciclar es muy importante.",
  "I always carry a reusable bag.|Siempre llevo una bolsa reutilizable.",
  "The river is polluted.|El río está contaminado.",
  "We should plant more trees.|Deberíamos plantar más árboles.",
  "The air quality is bad today.|La calidad del aire está mala hoy.",
  "I love the smell of fresh flowers.|Me encanta el olor de las flores frescas.",
  "The grass is green and soft.|La hierba es verde y suave.",
  "I like to walk barefoot on the sand.|Me gusta caminar descalzo en la arena.",
  "The waves are very strong today.|Las olas están muy fuertes hoy.",
  "I found a beautiful seashell.|Encontré una concha hermosa.",
  "The sunset over the ocean is magical.|El atardecer sobre el océano es mágico.",
  "I want to live by the sea.|Quiero vivir cerca del mar.",
  "My dream is to travel around the world.|Mi sueño es viajar por el mundo.",
  "I am saving money for a trip.|Estoy ahorrando dinero para un viaje.",
  "The hotel has a swimming pool.|El hotel tiene una piscina.",
  "I need to book a flight.|Necesito reservar un vuelo.",
  "The airport is thirty minutes away.|El aeropuerto está a treinta minutos.",
  "I prefer window seats on planes.|Prefiero los asientos de ventana en los aviones.",
  "The flight attendant served drinks.|La azafata sirvió bebidas.",
  "I felt turbulence during the flight.|Sentí turbulencia durante el vuelo.",
  "I arrived safely at my destination.|Llegué sano y salvo a mi destino.",
  "My luggage didn't arrive.|Mi equipaje no llegó.",
  "I need to report lost luggage.|Necesito reportar equipaje perdido.",
  "The customs officer asked me questions.|El oficial de aduanas me hizo preguntas.",
  "I have nothing to declare.|No tengo nada que declarar.",
  "I am here on business.|Estoy aquí por negocios.",
  "I have a meeting at three.|Tengo una reunión a las tres.",
  "The conference starts on Monday.|La conferencia empieza el lunes.",
  "I need to prepare a presentation.|Necesito preparar una presentación.",
  "The office is on the fifth floor.|La oficina está en el quinto piso.",
  "I work with a great team.|Trabajo con un equipo excelente.",
  "We need to finish this project soon.|Necesitamos terminar este proyecto pronto.",
  "I like my job.|Me gusta mi trabajo.",
  "I am looking for a new job.|Estoy buscando un nuevo trabajo.",
  "I have an interview tomorrow.|Tengo una entrevista mañana.",
  "Please send me your resume.|Por favor envíame tu currículum.",
  "You are hired!|¡Estás contratado!",
  "I got a promotion.|Recibí un ascenso.",
  "The salary is good.|El salario es bueno.",
  "I work from home on Fridays.|Trabajo desde casa los viernes.",
  "The deadline is next Friday.|La fecha límite es el próximo viernes.",
  "I need to make a phone call.|Necesito hacer una llamada.",
  "I will call you back later.|Te devolveré la llamada después.",
  "The line is busy.|La línea está ocupada.",
  "You have a voicemail.|Tienes un mensaje de voz.",
  "I didn't hear the phone ring.|No escuché sonar el teléfono.",
  "My phone battery died.|Se acabó la batería de mi teléfono.",
  "The screen is cracked.|La pantalla está agrietada.",
  "I dropped my phone in water.|Se me cayó el teléfono al agua.",
  "Can you recommend a good restaurant?|¿Puedes recomendar un buen restaurante?",
  "The service was excellent.|El servicio fue excelente.",
  "I am allergic to peanuts.|Soy alérgico al maní.",
  "Does this dish contain nuts?|¿Este plato contiene nueces?",
  "I would like the grilled fish.|Quisiera el pescado a la parrilla.",
  "Do you have vegetarian options?|¿Tienen opciones vegetarianas?",
  "I will have the salad.|Tomaré la ensalada.",
  "The bread is freshly baked.|El pan está recién horneado.",
  "I would like more bread, please.|Quisiera más pan, por favor.",
  "This wine is very good.|Este vino está muy bueno.",
  "I don't drink coffee after dinner.|No tomo café después de cenar.",
  "I prefer tea in the evening.|Prefiero té por la noche.",
  "The bathroom is occupied.|El baño está ocupado.",
  "There is no toilet paper.|No hay papel higiénico.",
  "Please clean the room.|Por favor limpia la habitación.",
  "I need fresh towels.|Necesito toallas limpias.",
  "The air conditioning is not working.|El aire acondicionado no funciona.",
  "The room is too cold.|La habitación está demasiado fría.",
  "I need an extra pillow.|Necesito una almohada extra.",
  "The bed is very comfortable.|La cama está muy cómoda.",
  "I had a good night's sleep.|Dormí bien por la noche.",
  "I woke up early this morning.|Me desperté temprano esta mañana.",
  "The view from my room is wonderful.|La vista desde mi habitación es maravillosa.",
  "I can see the mountains from here.|Puedo ver las montañas desde aquí.",
  "The city lights at night are beautiful.|Las luces de la ciudad de noche son hermosas.",
  "I want to explore the old town.|Quiero explorar el casco antiguo.",
  "The cathedral is very impressive.|La catedral es muy impresionante.",
  "We took a walking tour of the city.|Tomamos un tour a pie por la ciudad.",
  "The guide was very knowledgeable.|El guía tenía mucho conocimiento.",
  "I learned a lot about the history.|Aprendí mucho sobre la historia.",
  "The local market is colorful and lively.|El mercado local es colorido y animado.",
  "I bought some fresh fruit at the market.|Compré fruta fresca en el mercado.",
  "The street food is delicious.|La comida callejera es deliciosa.",
  "I tried a typical dish from the region.|Probé un plato típico de la región.",
  "It was very spicy but tasty.|Estaba muy picante pero sabroso.",
  "I prefer mild flavors.|Prefiero los sabores suaves.",
  "The music in the plaza is lovely.|La música en la plaza es encantadora.",
  "People are dancing in the street.|La gente está bailando en la calle.",
  "I want to learn to dance salsa.|Quiero aprender a bailar salsa.",
  "The festival lasts three days.|El festival dura tres días.",
  "There are fireworks at night.|Hay fuegos artificiales por la noche.",
  "The parade was very colorful.|El desfile fue muy colorido.",
  "I took many photos.|Tomé muchas fotos.",
  "I will remember this trip forever.|Recordaré este viaje para siempre.",
  "I want to come back again.|Quiero volver otra vez.",
  "This has been the best vacation ever.|Han sido las mejores vacaciones de mi vida.",
  "I feel relaxed and happy.|Me siento relajado y feliz.",
  "I don't want to go home.|No quiero volver a casa.",
  "I am back to work now.|Ya volví al trabajo.",
  "I miss the beach already.|Ya extraño la playa.",
  "I am planning my next trip.|Estoy planeando mi próximo viaje.",
  "Life is short, travel more.|La vida es corta, viaja más.",
]

function buildWords(prefix, data) {
  let id = 1
  const words = []
  for (const [count1, cat, entries] of data) {
    for (const entry of entries) {
      const parts = entry.split("|")
      const word = { id: `${prefix}-${id++}`, source: parts[0], target: parts[1], category: cat }
      if (parts[2]) word.transliteration = parts[2]
      words.push(word)
    }
  }
  return words
}

function buildSentences(prefix, list) {
  return list.map((entry, i) => {
    const parts = entry.split("|")
    const s = { id: `${prefix}-s-${i + 1}`, source: parts[0], target: parts[1] }
    if (parts[2]) s.transliteration = parts[2]
    return s
  })
}

const esWordsOut = buildWords("es", esWords)
const esSentencesOut = buildSentences("es", esSentences)

console.log(`Spanish: ${esWordsOut.length} words, ${esSentencesOut.length} sentences`)

function makeWordFile(lang, prefix, wordData, sentenceData) {
  let code = `import type { Word, Sentence } from "@/lib/types"\n\n`
  code += `export const ${lang}Words: Word[] = [\n`
  for (const w of wordData) {
    const tr = w.transliteration ? `, transliteration: "${w.transliteration}"` : ""
    code += `  { id: "${w.id}", source: "${w.source}", target: "${w.target}"${tr}, category: "${w.category}" },\n`
  }
  code += `]\n\n`
  code += `export const ${lang}Sentences: Sentence[] = [\n`
  for (const s of sentenceData) {
    const tr = s.transliteration ? `, transliteration: "${s.transliteration}"` : ""
    code += `  { id: "${s.id}", source: "${s.source}", target: "${s.target}"${tr} },\n`
  }
  code += `]\n`

  const dir = join(process.cwd(), "src", "data")
  const filePath = join(dir, `${lang}.ts`)
  writeFileSync(filePath, code, "utf8")
  console.log(`Wrote ${filePath}`)
}

makeWordFile("spanish", "es", esWordsOut, esSentencesOut)

// For Chinese and Arabic, we copy the sentence patterns with translated content
// but for this generation, we use a simplified approach
console.log("\nNow generating Chinese and Arabic data...")

// Chinese word data
const zhWords = esWords.map(([count, cat, entries]) => {
  // We'll use a lookup approach - just copy the structure and note that
  // Chinese needs transliteration
  return [count, cat, entries]
})

// For now, let's just output what we have and note Chinese/Arabic need manual translation
console.log("Spanish data generated successfully!")
console.log("Note: Chinese and Arabic data requires manual translation entries.")
console.log("To add them, edit the data files directly.")
